package api_add_backup_file

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "api_add_backup_file"
	self.Methods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 0
	self.Pattern = "/api/admin/root/add-backup-file/{Id:integer}/{*Path}"
	self.Category = "Backoffice Backups API"
	self.Summary = "Stores the body as one file of an open snapshot, at the path below the --database folder the address ends with; a path it already holds is replaced"
	self.Description = ""
	self.Examples = []string{"curl -X POST localhost:3000/api/admin/root/add-backup-file/1/backofficedb/backoffice-user/1/values/username -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/octet-stream' --data-binary @data/backofficedb/backoffice-user/1/values/username"}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "ApiAdminRootAddBackupFile",
			Start:       0,
			End:         3,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/api/admin/root/add-backup-file", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Id",
			Start:       4,
			End:         4,
			Type:        api.PathInteger,
			Description: "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Path",
			Start:       5,
			End:         -1,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "raw",
		Required:    true,
		MaxBytes:    268435456,
		ContentType: "application/octet-stream",
		Schema:      "",
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
