package main_database

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
)

// This file is generated by `agnos build` from specs.yaml — do not edit by hand.
// A query specs.yaml cannot describe goes in methods_custom.go, which no build
// reads and no build rewrites.

// MainDatabase is the main-database database: the handle it was built over and one
// function field per generated method. Building one is free — it touches no
// key and creates nothing until the first record is written — so whoever needs
// it calls New on the spot instead of reading it off the Sandbox.
type MainDatabase struct {
	sandbox *api.Sandbox
	handle  database.DatabaseHandle
}
