package main_database

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
	databaseio "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/generated/databaseio"
)

// This file is generated by `agnos build` from specs.yaml — do not edit by hand.
//
// Every function takes the sandbox first, the way every function of
// sandbox/internal/ does. A search answers (record, false) when there is
// nothing to find and a write answers an error when something went wrong; no
// stored value is ever asserted into a type without checking, so a malformed
// record is an error rather than a panic.

// AddAdminUsers inserts one admin-users record.
func AddAdminUsers(sandbox *api.Sandbox, self *MainDatabase, props AdminUsersNew) (AdminUsersItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "admin-users")
	if err != nil {
		return AdminUsersItem{}, err
	}
	item, failure := schema.NewItem(newAdminUsersFields(props))
	if failure != nil {
		return AdminUsersItem{}, databaseio.Fail(sandbox, failure)
	}
	return buildAdminUsersItem(sandbox, item)
}

// FindAdminUsersById reads one admin-users record by its permanent id.
func FindAdminUsersById(sandbox *api.Sandbox, self *MainDatabase, id int64) (AdminUsersItem, bool) {
	schema, err := databaseio.Schema(sandbox, self.handle, "admin-users")
	if err != nil {
		sandbox.Deps.Std.Log("FindAdminUsersById: %s \n", err.Error())
		return AdminUsersItem{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return AdminUsersItem{}, false
	}
	built, err := buildAdminUsersItem(sandbox, item)
	if err != nil {
		sandbox.Deps.Std.Log("FindAdminUsersById: %s \n", err.Error())
		return AdminUsersItem{}, false
	}
	return built, true
}

// ListAdminUsers reads every admin-users record the filtrage keeps.
func ListAdminUsers(sandbox *api.Sandbox, self *MainDatabase, filtrage AdminUsersFiltrage) ([]AdminUsersItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "admin-users")
	if err != nil {
		return nil, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	kept := []AdminUsersItem{}
	for _, item := range items {
		built, err := buildAdminUsersItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		if !matchAdminUsers(sandbox, built, filtrage) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
}

// PageAdminUsers reads one page of admin-users records, counted from 1.
func PageAdminUsers(sandbox *api.Sandbox, self *MainDatabase, position int, chunk int) ([]AdminUsersItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "admin-users")
	if err != nil {
		return nil, err
	}
	items, failure := schema.List(position, chunk)
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	page := []AdminUsersItem{}
	for _, item := range items {
		built, err := buildAdminUsersItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
}

// CountAdminUsers is how many admin-users records are live.
func CountAdminUsers(sandbox *api.Sandbox, self *MainDatabase) (int, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "admin-users")
	if err != nil {
		return 0, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return 0, databaseio.Fail(sandbox, failure)
	}
	return len(items), nil
}

// RemoveAdminUsers deletes one admin-users record and everything nested under it.
func RemoveAdminUsers(sandbox *api.Sandbox, self *MainDatabase, id int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "admin-users")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("admin-users %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Remove())
}

// newAdminUsersFields is one insert into admin-users as the stored field map.
func newAdminUsersFields(props AdminUsersNew) map[string]any {
	return map[string]any{}
}

// buildAdminUsersItem reads one stored admin-users record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildAdminUsersItem(sandbox *api.Sandbox, item database.SchemaItem) (AdminUsersItem, error) {
	built := AdminUsersItem{Id: item.Id}

	return built, nil
}

// matchAdminUsers is one AdminUsersFiltrage applied to one record. A zero value
// never filters, so an empty filtrage keeps everything.
func matchAdminUsers(sandbox *api.Sandbox, item AdminUsersItem, filtrage AdminUsersFiltrage) bool {
	return true
}
