package main_database

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
)

// New builds the main-database database from the Props its specs.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a handle over a prefix, so building one creates nothing until the first
// record is written.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *MainDatabase {
	props := database.Props{
		Path: "main-database",
		Schemas: []database.Schema{
			{
				Name:  "admin-users",
				Itens: []database.Item{},
			},
		},
	}

	self := MainDatabase{sandbox: sandbox}
	self.handle = sandbox.Deps.Database.Databases.New(props)

	self.AddAdminUsers = func(props AdminUsersNew) (AdminUsersItem, error) {
		return AddAdminUsers(self.sandbox, &self, props)
	}
	self.FindAdminUsersById = func(id int64) (AdminUsersItem, bool) {
		return FindAdminUsersById(self.sandbox, &self, id)
	}
	self.ListAdminUsers = func(filtrage AdminUsersFiltrage) ([]AdminUsersItem, error) {
		return ListAdminUsers(self.sandbox, &self, filtrage)
	}
	self.PageAdminUsers = func(position int, chunk int) ([]AdminUsersItem, error) {
		return PageAdminUsers(self.sandbox, &self, position, chunk)
	}
	self.CountAdminUsers = func() (int, error) {
		return CountAdminUsers(self.sandbox, &self)
	}
	self.RemoveAdminUsers = func(id int64) error {
		return RemoveAdminUsers(self.sandbox, &self, id)
	}

	return &self
}
