package create_backup_form

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	serializabledeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serializabledeps"
)

// Input is every value this route reads off a request, one field per entry
// of its route.yaml: FullRoute, the whole request path, then one per entry of
// `paths` and one per entry of `parameters`, then Body when the route declares
// one, each tagged with the id the generic Run fills it by. Handle is handed
// one, already filled.
// Generated by `agnos build` — do not edit by hand.
type Input struct {
	FullRoute             string `id:"FullRoute"`
	AdminRootCreateBackup string `id:"AdminRootCreateBackup"`
	Body                  Body   `id:"Body"`
}

// Body is one object of this route's declared form-schema, as the
// generated ReadBody hands it over.
type Body struct {
	Name string
}

// MaxBodyBytes is the largest request body this route reads, from the
// `max-bytes` of its declaration. A longer one is answered 413.
const MaxBodyBytes = 1048576

// BodySchema is this route's declared form-schema in canonical form — the text
// Deps.OpinionatedAgnosServer.ValidateForm checks a request body against.
const BodySchema = "{\"properties\":{\"name\":{\"maxLength\":100,\"type\":\"string\"}},\"type\":\"object\"}"

// ReadBody reads, validates and converts the request body of one bound route.
// The generic Run calls it — through the ReadBody new.go closes over
// the sandbox — before Handle runs, and binds what it returns onto
// Input.Body; a middleware in front of this route may still refuse a request
// before a byte of it is read.
//
// It returns nil when the body passed. Any other failure comes back built by
// Deps.OpinionatedAgnosServer.Fail, which the lib's dispatch raises — reaching
// this project's own HandleBadRequest or HandlePayloadTooLarge — and the handler never
// runs.
func ReadBody(sandbox *api.Sandbox, route *api.Route) (Body, error) {
	var body Body

	raw, err := route.Request.ReadBody(MaxBodyBytes)
	if err != nil {
		return body, sandbox.Deps.OpinionatedAgnosServer.FailWithCause(api.StatusPayloadTooLarge, "",
			"the request body is larger than 1048576 bytes", err.Error())
	}

	if len(raw) == 0 {
		// An absent form is read as an empty one, so a property the
		// schema requires is still reported missing.
	}

	form, err := route.Request.ReadForm(MaxBodyBytes)
	if err != nil {
		return body, sandbox.Deps.OpinionatedAgnosServer.FailWithCause(api.StatusBadRequest, "",
			"the request body is not a valid form", err.Error())
	}

	parsed, field, message, ok := sandbox.Deps.OpinionatedAgnosServer.ValidateForm(sandbox.Deps.SerializableDeps, BodySchema, form)
	if !ok {
		return body, sandbox.Deps.OpinionatedAgnosServer.Fail(api.StatusBadRequest, field, message)
	}

	body = bindBody(sandbox, parsed)

	return body, nil
}

// bindBody converts one already-validated document into Body. The
// schema has been enforced by then, so a property that will not read was
// optional and comes back as its zero value.
func bindBody(sandbox *api.Sandbox, document *serializabledeps.SerializableObject) Body {
	value := Body{}
	value.Name = sandbox.Deps.OpinionatedAgnosServer.ReadString(document, "name")
	return value
}
