package same_origin

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinatedAgnosServer.NewRoute, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinatedAgnosServer.NewRoute()

	self.Name = "same_origin"
	self.AcceptMethods = []string{"ANY"}
	self.Priority = 9
	self.ResponseType = "application/json"
	self.Segments = 0
	self.Pattern = "/admin/*"
	self.Category = "Middleware"
	self.Help = "Refuses a request to /admin another site's page sent"
	self.LongDescription = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Route",
			Start:       0,
			End:         -1,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.PrefixTrigger, Value: "/admin", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "Origin",
			Key:         "origin",
			Fonts:       []api.ParameterFont{api.HeaderParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the origin of the page that sent the request, sent by the browser",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Host",
			Key:         "host",
			Fonts:       []api.ParameterFont{api.HeaderParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the host the request was sent to",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
