package list_backoffice_users_page

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "list_backoffice_users_page"
	self.Methods = []string{"GET"}
	self.Priority = 100
	self.ResponseType = "text/html"
	self.Segments = 2
	self.Pattern = "/admin/list-backoffice-users"
	self.Category = "Backoffice Users"
	self.Summary = "Lists backoffice users, filtered and paginated"
	self.Description = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "AdminListBackofficeUsers",
			Start:       0,
			End:         1,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/admin/list-backoffice-users", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "Search",
			Key:         "search",
			Sources:     []api.ParameterSource{api.SourceQuery},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "matches the username or the email, case-insensitive",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Role",
			Key:         "role",
			Sources:     []api.ParameterSource{api.SourceQuery},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "root, viewer, or empty for every role",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Page",
			Key:         "page",
			Sources:     []api.ParameterSource{api.SourceQuery},
			Required:    false,
			Type:        api.ParameterInteger,
			Default:     "1",
			HasDefault:  true,
			Description: "the page to show, counted from 1",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Limit",
			Key:         "limit",
			Sources:     []api.ParameterSource{api.SourceQuery},
			Required:    false,
			Type:        api.ParameterInteger,
			Default:     "20",
			HasDefault:  true,
			Description: "how many users a page shows, from 1 to 100",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Notice",
			Key:         "notice",
			Sources:     []api.ParameterSource{api.SourceQuery},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "the outcome code of the last add, edit or remove",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
