// Code generated by agnos. DO NOT EDIT.

package backoffice_login

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/generated.new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "backoffice_login"
	self.Methods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "text/html"
	self.Segments = 2
	self.Pattern = "/admin/login"
	self.Category = "Backoffice"
	self.Summary = "Signs a backoffice user in and sets the session cookie"
	self.Description = "The username field takes a username or an email. A match sets the session cookie and redirects to /admin/home; anything else answers the login page under a 401. After 20 failed sign-ins from one client ip, or 10 on one login, in 15 minutes, every attempt is answered the login page under a 429 with Retry-After, its password unchecked, until the 15 minutes pass."
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "AdminLogin",
			Start:       0,
			End:         1,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/admin/login", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "form",
		Required:    true,
		MaxBytes:    1048576,
		ContentType: "application/x-www-form-urlencoded",
		Schema:      BodySchema,
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
