package get_transactions

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeio"
)

// NewRoute builds this route's declaration — the whole of what its route.yaml
// says — and closes RouteHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) api.Route {
	route := api.NewRoute()

	route.Name = "get_transactions"
	route.Method = "GET"
	route.Pattern = "/transactions"
	route.Category = "Transactions"
	route.Help = "List transactions"
	route.LongDescription = ""
	route.Examples = []string{}
	route.Hidden = false

	route.Paths = []api.RoutePath{
		{
			Identifier: "/transactions",
		},
	}

	route.Headers = []api.RouteField{}

	route.Params = []api.RouteField{}

	route.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	route.Handler = func(bound *api.Route) int {
		return RouteHandler(sandbox, bound, routeio.ResponseOf(bound))
	}

	return *route
}
