package backoffice_db

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// This file is generated by `agnos build` from database.yaml — do not edit by hand.
// A query database.yaml cannot describe goes in methods_custom.go, which no build
// reads and no build rewrites.

// BackofficeUserRecord is one stored backoffice-user record: its permanent id and every
// plain field the declaration gives it.
type BackofficeUserRecord struct {
	Id           int64
	Username     string
	Email        string
	PasswordHash string
	Role         int64
}

// BackofficeUserInput is one insert into backoffice-user: the fields a new record carries.
type BackofficeUserInput struct {
	Username     string
	Email        string
	PasswordHash string
	Role         int64
}

// BackofficeUserFilter narrows a ListBackofficeUser. Every plain field is here, because
// only a `key` field is indexed and this is the one way to reach the rest. A
// zero value turns its own filter off.
type BackofficeUserFilter struct {
	UsernameStartsWith     string
	UsernameEquals         string
	EmailStartsWith        string
	EmailEquals            string
	PasswordHashStartsWith string
	PasswordHashEquals     string
	RoleMin                int64
	RoleMax                int64
}

// BackofficeUserSessionRecord is one stored session record: its permanent id and every
// plain field the declaration gives it.
type BackofficeUserSessionRecord struct {
	Id        int64
	ExpiresAt int64
}

// BackofficeUserSessionInput is one insert into session: the fields a new record carries.
type BackofficeUserSessionInput struct {
	ExpiresAt int64
}

// ApiTokenRecord is one stored api-token record: its permanent id and every
// plain field the declaration gives it.
type ApiTokenRecord struct {
	Id          int64
	TokenSha256 string
	Name        string
	Prefix      string
	OwnerId     int64
	CreatedAt   int64
	ExpiresAt   int64
	Ips         string
	LastUsedAt  int64
	LastUsedIp  string
}

// ApiTokenInput is one insert into api-token: the fields a new record carries.
type ApiTokenInput struct {
	TokenSha256 string
	Name        string
	Prefix      string
	OwnerId     int64
	CreatedAt   int64
	ExpiresAt   int64
	Ips         string
	LastUsedAt  int64
	LastUsedIp  string
}

// ApiTokenFilter narrows a ListApiToken. Every plain field is here, because
// only a `key` field is indexed and this is the one way to reach the rest. A
// zero value turns its own filter off.
type ApiTokenFilter struct {
	TokenSha256StartsWith string
	TokenSha256Equals     string
	NameStartsWith        string
	NameEquals            string
	PrefixStartsWith      string
	PrefixEquals          string
	OwnerIdMin            int64
	OwnerIdMax            int64
	CreatedAtMin          int64
	CreatedAtMax          int64
	ExpiresAtMin          int64
	ExpiresAtMax          int64
	IpsStartsWith         string
	IpsEquals             string
	LastUsedAtMin         int64
	LastUsedAtMax         int64
	LastUsedIpStartsWith  string
	LastUsedIpEquals      string
}

// BackofficeDb is the backoffice-db database: the handle it was built over and one
// function field per generated method. Building one is free — it touches no
// key and creates nothing until the first record is written — so whoever needs
// it calls New on the spot instead of reading it off the Sandbox.
type BackofficeDb struct {
	sandbox *api.Sandbox
	handle  databasedeps.DatabaseHandle

	// AddBackofficeUser inserts one backoffice-user record.
	AddBackofficeUser func(props BackofficeUserInput) (BackofficeUserRecord, error)
	// FindBackofficeUserById reads one backoffice-user record by its permanent id.
	FindBackofficeUserById func(id int64) (BackofficeUserRecord, bool)
	// ListBackofficeUsers reads every backoffice-user record the filter keeps.
	ListBackofficeUsers func(filter BackofficeUserFilter) ([]BackofficeUserRecord, error)
	// ListBackofficeUsersPage reads up to limit backoffice-user records after the first offset, every one past them when limit is 0.
	ListBackofficeUsersPage func(offset int, limit int) ([]BackofficeUserRecord, error)
	// CountBackofficeUser is how many backoffice-user records are live.
	CountBackofficeUser func() (int, error)
	// SetBackofficeUserUsername writes a new username on one backoffice-user record.
	SetBackofficeUserUsername func(id int64, value string) error
	// SetBackofficeUserEmail writes a new email on one backoffice-user record.
	SetBackofficeUserEmail func(id int64, value string) error
	// SetBackofficeUserPasswordHash writes a new password-hash on one backoffice-user record.
	SetBackofficeUserPasswordHash func(id int64, value string) error
	// SetBackofficeUserRole writes a new role on one backoffice-user record.
	SetBackofficeUserRole func(id int64, value int64) error
	// RemoveBackofficeUser deletes one backoffice-user record and everything nested under it.
	RemoveBackofficeUser func(id int64) error
	// AddBackofficeUserSession inserts one session record under one backoffice-user record.
	AddBackofficeUserSession func(parentId int64, props BackofficeUserSessionInput) (BackofficeUserSessionRecord, error)
	// ListBackofficeUserSessions reads every session record of one backoffice-user record.
	ListBackofficeUserSessions func(parentId int64) ([]BackofficeUserSessionRecord, error)
	// AddApiToken inserts one api-token record.
	AddApiToken func(props ApiTokenInput) (ApiTokenRecord, error)
	// FindApiTokenById reads one api-token record by its permanent id.
	FindApiTokenById func(id int64) (ApiTokenRecord, bool)
	// FindApiTokenByTokenSha256 reads one api-token record by its indexed token-sha256.
	FindApiTokenByTokenSha256 func(value string) (ApiTokenRecord, bool)
	// ListApiTokens reads every api-token record the filter keeps.
	ListApiTokens func(filter ApiTokenFilter) ([]ApiTokenRecord, error)
	// ListApiTokensPage reads up to limit api-token records after the first offset, every one past them when limit is 0.
	ListApiTokensPage func(offset int, limit int) ([]ApiTokenRecord, error)
	// CountApiToken is how many api-token records are live.
	CountApiToken func() (int, error)
	// SetApiTokenTokenSha256 writes a new token-sha256 on one api-token record.
	SetApiTokenTokenSha256 func(id int64, value string) error
	// SetApiTokenName writes a new name on one api-token record.
	SetApiTokenName func(id int64, value string) error
	// SetApiTokenPrefix writes a new prefix on one api-token record.
	SetApiTokenPrefix func(id int64, value string) error
	// SetApiTokenOwnerId writes a new owner-id on one api-token record.
	SetApiTokenOwnerId func(id int64, value int64) error
	// SetApiTokenCreatedAt writes a new created-at on one api-token record.
	SetApiTokenCreatedAt func(id int64, value int64) error
	// SetApiTokenExpiresAt writes a new expires-at on one api-token record.
	SetApiTokenExpiresAt func(id int64, value int64) error
	// SetApiTokenIps writes a new ips on one api-token record.
	SetApiTokenIps func(id int64, value string) error
	// SetApiTokenLastUsedAt writes a new last-used-at on one api-token record.
	SetApiTokenLastUsedAt func(id int64, value int64) error
	// SetApiTokenLastUsedIp writes a new last-used-ip on one api-token record.
	SetApiTokenLastUsedIp func(id int64, value string) error
	// RemoveApiToken deletes one api-token record and everything nested under it.
	RemoveApiToken func(id int64) error
}
