package backoffice_db

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// This file is generated by `agnos build` from database.yaml — do not edit by hand.
//
// Every function takes the sandbox first, the way every function of
// sandbox/internal/ does. A search answers (record, false) when there is
// nothing to find and a write answers an error when something went wrong; no
// stored value is ever asserted into a type without checking, so a malformed
// record is an error rather than a panic.

// AddBackofficeUser inserts one backoffice-user record.
func AddBackofficeUser(sandbox *api.Sandbox, self *BackofficeDb, props BackofficeUserInput) (BackofficeUserRecord, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return BackofficeUserRecord{}, err
	}
	item, failure := schema.NewItem(newBackofficeUserFields(props))
	if failure != nil {
		return BackofficeUserRecord{}, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return buildBackofficeUserRecord(sandbox, item)
}

// FindBackofficeUserById reads one backoffice-user record by its permanent id.
func FindBackofficeUserById(sandbox *api.Sandbox, self *BackofficeDb, id int64) (BackofficeUserRecord, bool) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindBackofficeUserById: %s \n", err.Error())
		return BackofficeUserRecord{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return BackofficeUserRecord{}, false
	}
	built, err := buildBackofficeUserRecord(sandbox, item)
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindBackofficeUserById: %s \n", err.Error())
		return BackofficeUserRecord{}, false
	}
	return built, true
}

// ListBackofficeUsers reads every backoffice-user record the filter keeps.
func ListBackofficeUsers(sandbox *api.Sandbox, self *BackofficeDb, filter BackofficeUserFilter) ([]BackofficeUserRecord, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return nil, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return nil, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	kept := []BackofficeUserRecord{}
	for _, item := range items {
		built, err := buildBackofficeUserRecord(sandbox, item)
		if err != nil {
			return nil, err
		}
		if !matchBackofficeUser(sandbox, built, filter) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
}

// ListBackofficeUsersPage reads up to limit backoffice-user records after the first offset, every one past them when limit is 0.
func ListBackofficeUsersPage(sandbox *api.Sandbox, self *BackofficeDb, offset int, limit int) ([]BackofficeUserRecord, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return nil, err
	}
	items, failure := schema.List(offset+1, limit)
	if failure != nil {
		return nil, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	page := []BackofficeUserRecord{}
	for _, item := range items {
		built, err := buildBackofficeUserRecord(sandbox, item)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
}

// CountBackofficeUser is how many backoffice-user records are live.
func CountBackofficeUser(sandbox *api.Sandbox, self *BackofficeDb) (int, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return 0, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return 0, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return len(items), nil
}

// SetBackofficeUserUsername writes a new username on one backoffice-user record.
func SetBackofficeUserUsername(sandbox *api.Sandbox, self *BackofficeDb, id int64, value string) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("backoffice-user %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("username", value))
}

// SetBackofficeUserEmail writes a new email on one backoffice-user record.
func SetBackofficeUserEmail(sandbox *api.Sandbox, self *BackofficeDb, id int64, value string) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("backoffice-user %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("email", value))
}

// SetBackofficeUserPasswordHash writes a new password-hash on one backoffice-user record.
func SetBackofficeUserPasswordHash(sandbox *api.Sandbox, self *BackofficeDb, id int64, value string) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("backoffice-user %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("password-hash", value))
}

// SetBackofficeUserRole writes a new role on one backoffice-user record.
func SetBackofficeUserRole(sandbox *api.Sandbox, self *BackofficeDb, id int64, value int64) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("backoffice-user %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("role", value))
}

// RemoveBackofficeUser deletes one backoffice-user record and everything nested under it.
func RemoveBackofficeUser(sandbox *api.Sandbox, self *BackofficeDb, id int64) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("backoffice-user %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Remove())
}

// AddBackofficeUserSession inserts one session record under one backoffice-user record.
func AddBackofficeUserSession(sandbox *api.Sandbox, self *BackofficeDb, parentId int64, props BackofficeUserSessionInput) (BackofficeUserSessionRecord, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return BackofficeUserSessionRecord{}, err
	}
	parent, ok := schema.FindById(parentId)
	if !ok {
		return BackofficeUserSessionRecord{}, sandbox.Deps.StdDeps.Errorf("backoffice-user %d not found", parentId)
	}
	item, failure := parent.NewSubItem("session", newBackofficeUserSessionFields(props))
	if failure != nil {
		return BackofficeUserSessionRecord{}, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return buildBackofficeUserSessionRecord(sandbox, item)
}

// ListBackofficeUserSessions reads every session record of one backoffice-user record.
func ListBackofficeUserSessions(sandbox *api.Sandbox, self *BackofficeDb, parentId int64) ([]BackofficeUserSessionRecord, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "backoffice-user")
	if err != nil {
		return nil, err
	}
	parent, ok := schema.FindById(parentId)
	if !ok {
		return nil, sandbox.Deps.StdDeps.Errorf("backoffice-user %d not found", parentId)
	}
	nested := []BackofficeUserSessionRecord{}
	for _, item := range parent.ListAll("session") {
		built, err := buildBackofficeUserSessionRecord(sandbox, item)
		if err != nil {
			return nil, err
		}
		nested = append(nested, built)
	}
	return nested, nil
}

// AddApiToken inserts one api-token record.
func AddApiToken(sandbox *api.Sandbox, self *BackofficeDb, props ApiTokenInput) (ApiTokenRecord, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return ApiTokenRecord{}, err
	}
	item, failure := schema.NewItem(newApiTokenFields(props))
	if failure != nil {
		return ApiTokenRecord{}, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return buildApiTokenRecord(sandbox, item)
}

// FindApiTokenById reads one api-token record by its permanent id.
func FindApiTokenById(sandbox *api.Sandbox, self *BackofficeDb, id int64) (ApiTokenRecord, bool) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindApiTokenById: %s \n", err.Error())
		return ApiTokenRecord{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return ApiTokenRecord{}, false
	}
	built, err := buildApiTokenRecord(sandbox, item)
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindApiTokenById: %s \n", err.Error())
		return ApiTokenRecord{}, false
	}
	return built, true
}

// FindApiTokenByTokenSha256 reads one api-token record by its indexed token-sha256.
func FindApiTokenByTokenSha256(sandbox *api.Sandbox, self *BackofficeDb, value string) (ApiTokenRecord, bool) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindApiTokenByTokenSha256: %s \n", err.Error())
		return ApiTokenRecord{}, false
	}
	item, ok := schema.FindByKey("token-sha256", value)
	if !ok {
		return ApiTokenRecord{}, false
	}
	built, err := buildApiTokenRecord(sandbox, item)
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindApiTokenByTokenSha256: %s \n", err.Error())
		return ApiTokenRecord{}, false
	}
	return built, true
}

// ListApiTokens reads every api-token record the filter keeps.
func ListApiTokens(sandbox *api.Sandbox, self *BackofficeDb, filter ApiTokenFilter) ([]ApiTokenRecord, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return nil, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return nil, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	kept := []ApiTokenRecord{}
	for _, item := range items {
		built, err := buildApiTokenRecord(sandbox, item)
		if err != nil {
			return nil, err
		}
		if !matchApiToken(sandbox, built, filter) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
}

// ListApiTokensPage reads up to limit api-token records after the first offset, every one past them when limit is 0.
func ListApiTokensPage(sandbox *api.Sandbox, self *BackofficeDb, offset int, limit int) ([]ApiTokenRecord, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return nil, err
	}
	items, failure := schema.List(offset+1, limit)
	if failure != nil {
		return nil, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	page := []ApiTokenRecord{}
	for _, item := range items {
		built, err := buildApiTokenRecord(sandbox, item)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
}

// CountApiToken is how many api-token records are live.
func CountApiToken(sandbox *api.Sandbox, self *BackofficeDb) (int, error) {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return 0, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return 0, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return len(items), nil
}

// SetApiTokenTokenSha256 writes a new token-sha256 on one api-token record.
func SetApiTokenTokenSha256(sandbox *api.Sandbox, self *BackofficeDb, id int64, value string) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("token-sha256", value))
}

// SetApiTokenName writes a new name on one api-token record.
func SetApiTokenName(sandbox *api.Sandbox, self *BackofficeDb, id int64, value string) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("name", value))
}

// SetApiTokenPrefix writes a new prefix on one api-token record.
func SetApiTokenPrefix(sandbox *api.Sandbox, self *BackofficeDb, id int64, value string) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("prefix", value))
}

// SetApiTokenOwnerId writes a new owner-id on one api-token record.
func SetApiTokenOwnerId(sandbox *api.Sandbox, self *BackofficeDb, id int64, value int64) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("owner-id", value))
}

// SetApiTokenCreatedAt writes a new created-at on one api-token record.
func SetApiTokenCreatedAt(sandbox *api.Sandbox, self *BackofficeDb, id int64, value int64) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("created-at", value))
}

// SetApiTokenExpiresAt writes a new expires-at on one api-token record.
func SetApiTokenExpiresAt(sandbox *api.Sandbox, self *BackofficeDb, id int64, value int64) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("expires-at", value))
}

// SetApiTokenIps writes a new ips on one api-token record.
func SetApiTokenIps(sandbox *api.Sandbox, self *BackofficeDb, id int64, value string) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("ips", value))
}

// SetApiTokenLastUsedAt writes a new last-used-at on one api-token record.
func SetApiTokenLastUsedAt(sandbox *api.Sandbox, self *BackofficeDb, id int64, value int64) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("last-used-at", value))
}

// SetApiTokenLastUsedIp writes a new last-used-ip on one api-token record.
func SetApiTokenLastUsedIp(sandbox *api.Sandbox, self *BackofficeDb, id int64, value string) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Update("last-used-ip", value))
}

// RemoveApiToken deletes one api-token record and everything nested under it.
func RemoveApiToken(sandbox *api.Sandbox, self *BackofficeDb, id int64) error {
	schema, err := sandbox.Deps.OpinionatedAgnosDatabase.Schema(self.handle, "api-token")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("api-token %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(item.Remove())
}

// newBackofficeUserFields is one insert into backoffice-user as the stored field map.
func newBackofficeUserFields(props BackofficeUserInput) map[string]any {
	return map[string]any{
		"username":      props.Username,
		"email":         props.Email,
		"password-hash": props.PasswordHash,
		"role":          props.Role,
	}
}

// buildBackofficeUserRecord reads one stored backoffice-user record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildBackofficeUserRecord(sandbox *api.Sandbox, item databasedeps.SchemaItem) (BackofficeUserRecord, error) {
	built := BackofficeUserRecord{Id: item.Id}

	valueUsername, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(item, "username")
	if err != nil {
		return built, err
	}
	built.Username = valueUsername

	valueEmail, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(item, "email")
	if err != nil {
		return built, err
	}
	built.Email = valueEmail

	valuePasswordHash, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(item, "password-hash")
	if err != nil {
		return built, err
	}
	built.PasswordHash = valuePasswordHash

	valueRole, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadInt(item, "role")
	if err != nil {
		return built, err
	}
	built.Role = valueRole

	return built, nil
}

// matchBackofficeUser is one BackofficeUserFilter applied to one record. A zero value
// never filters, so an empty filter keeps everything.
func matchBackofficeUser(sandbox *api.Sandbox, item BackofficeUserRecord, filter BackofficeUserFilter) bool {
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.Username, filter.UsernameStartsWith, filter.UsernameEquals) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.Email, filter.EmailStartsWith, filter.EmailEquals) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.PasswordHash, filter.PasswordHashStartsWith, filter.PasswordHashEquals) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.IntInRange(item.Role, filter.RoleMin, filter.RoleMax) {
		return false
	}
	return true
}

// newBackofficeUserSessionFields is one insert into session as the stored field map.
func newBackofficeUserSessionFields(props BackofficeUserSessionInput) map[string]any {
	return map[string]any{
		"expires-at": props.ExpiresAt,
	}
}

// buildBackofficeUserSessionRecord reads one stored session record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildBackofficeUserSessionRecord(sandbox *api.Sandbox, item databasedeps.SchemaItem) (BackofficeUserSessionRecord, error) {
	built := BackofficeUserSessionRecord{Id: item.Id}

	valueExpiresAt, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadInt(item, "expires-at")
	if err != nil {
		return built, err
	}
	built.ExpiresAt = valueExpiresAt

	return built, nil
}

// newApiTokenFields is one insert into api-token as the stored field map.
func newApiTokenFields(props ApiTokenInput) map[string]any {
	return map[string]any{
		"token-sha256": props.TokenSha256,
		"name":         props.Name,
		"prefix":       props.Prefix,
		"owner-id":     props.OwnerId,
		"created-at":   props.CreatedAt,
		"expires-at":   props.ExpiresAt,
		"ips":          props.Ips,
		"last-used-at": props.LastUsedAt,
		"last-used-ip": props.LastUsedIp,
	}
}

// buildApiTokenRecord reads one stored api-token record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildApiTokenRecord(sandbox *api.Sandbox, item databasedeps.SchemaItem) (ApiTokenRecord, error) {
	built := ApiTokenRecord{Id: item.Id}

	valueTokenSha256, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(item, "token-sha256")
	if err != nil {
		return built, err
	}
	built.TokenSha256 = valueTokenSha256

	valueName, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(item, "name")
	if err != nil {
		return built, err
	}
	built.Name = valueName

	valuePrefix, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(item, "prefix")
	if err != nil {
		return built, err
	}
	built.Prefix = valuePrefix

	valueOwnerId, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadInt(item, "owner-id")
	if err != nil {
		return built, err
	}
	built.OwnerId = valueOwnerId

	valueCreatedAt, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadInt(item, "created-at")
	if err != nil {
		return built, err
	}
	built.CreatedAt = valueCreatedAt

	valueExpiresAt, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadInt(item, "expires-at")
	if err != nil {
		return built, err
	}
	built.ExpiresAt = valueExpiresAt

	valueIps, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(item, "ips")
	if err != nil {
		return built, err
	}
	built.Ips = valueIps

	valueLastUsedAt, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadInt(item, "last-used-at")
	if err != nil {
		return built, err
	}
	built.LastUsedAt = valueLastUsedAt

	valueLastUsedIp, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(item, "last-used-ip")
	if err != nil {
		return built, err
	}
	built.LastUsedIp = valueLastUsedIp

	return built, nil
}

// matchApiToken is one ApiTokenFilter applied to one record. A zero value
// never filters, so an empty filter keeps everything.
func matchApiToken(sandbox *api.Sandbox, item ApiTokenRecord, filter ApiTokenFilter) bool {
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.TokenSha256, filter.TokenSha256StartsWith, filter.TokenSha256Equals) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.Name, filter.NameStartsWith, filter.NameEquals) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.Prefix, filter.PrefixStartsWith, filter.PrefixEquals) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.IntInRange(item.OwnerId, filter.OwnerIdMin, filter.OwnerIdMax) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.IntInRange(item.CreatedAt, filter.CreatedAtMin, filter.CreatedAtMax) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.IntInRange(item.ExpiresAt, filter.ExpiresAtMin, filter.ExpiresAtMax) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.Ips, filter.IpsStartsWith, filter.IpsEquals) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.IntInRange(item.LastUsedAt, filter.LastUsedAtMin, filter.LastUsedAtMax) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.LastUsedIp, filter.LastUsedIpStartsWith, filter.LastUsedIpEquals) {
		return false
	}
	return true
}
