package backoffice_db

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// New builds the backoffice-db database from the Props its database.yaml declares and
// closes every method of methods.go over it. Its key-prefix is a path inside
// sandbox.Config.DatabaseDir, the folder --database names. It touches no key:
// a database is a value over a prefix, so building one creates nothing until
// the first record is written. Props that Databases.New refuses are reported on stderr,
// and every method of the database then fails rather than panics; verify
// refuses every declaration that would build them.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *BackofficeDb {
	props := databasedeps.Props{
		Path: sandbox.Config.DatabaseDir + "/backofficedb",
		Schemas: []databasedeps.Schema{
			{
				Name: "backoffice-user",
				Fields: []databasedeps.Field{
					{Name: "username", Type: databasedeps.String, Required: true},
					{Name: "email", Type: databasedeps.String, Required: true},
					{Name: "password-hash", Type: databasedeps.String, Required: true},
					{Name: "role", Type: databasedeps.Int},
					{Name: "session", Type: databasedeps.Nested, Fields: []databasedeps.Field{
						{Name: "expires-at", Type: databasedeps.Int, Required: true}}},
				},
			},
			{
				Name: "api-token",
				Fields: []databasedeps.Field{
					{Name: "token-sha256", Type: databasedeps.Key, Required: true},
					{Name: "name", Type: databasedeps.String, Required: true},
					{Name: "prefix", Type: databasedeps.String, Required: true},
					{Name: "owner-id", Type: databasedeps.Int},
					{Name: "created-at", Type: databasedeps.Int},
					{Name: "expires-at", Type: databasedeps.Int},
					{Name: "ips", Type: databasedeps.String},
					{Name: "last-used-at", Type: databasedeps.Int},
					{Name: "last-used-ip", Type: databasedeps.String},
				},
			},
		},
	}

	database, failure := sandbox.Deps.DatabaseDeps.Databases.New(props)
	if failure != nil {
		sandbox.Deps.StdDeps.Eprintf("backoffice-db: %s \n", sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure).Error())
	}

	self := BackofficeDb{sandbox: sandbox, database: database}

	self.AddBackofficeUser = func(props BackofficeUserInput) (BackofficeUserRecord, error) {
		return AddBackofficeUser(self.sandbox, &self, props)
	}
	self.FindBackofficeUserById = func(id int64) (BackofficeUserRecord, bool) {
		return FindBackofficeUserById(self.sandbox, &self, id)
	}
	self.ListBackofficeUsers = func(filter BackofficeUserFilter) ([]BackofficeUserRecord, error) {
		return ListBackofficeUsers(self.sandbox, &self, filter)
	}
	self.ListBackofficeUsersPage = func(offset int, limit int) ([]BackofficeUserRecord, error) {
		return ListBackofficeUsersPage(self.sandbox, &self, offset, limit)
	}
	self.CountBackofficeUser = func() (int, error) {
		return CountBackofficeUser(self.sandbox, &self)
	}
	self.SetBackofficeUserUsername = func(id int64, value string) error {
		return SetBackofficeUserUsername(self.sandbox, &self, id, value)
	}
	self.SetBackofficeUserEmail = func(id int64, value string) error {
		return SetBackofficeUserEmail(self.sandbox, &self, id, value)
	}
	self.SetBackofficeUserPasswordHash = func(id int64, value string) error {
		return SetBackofficeUserPasswordHash(self.sandbox, &self, id, value)
	}
	self.SetBackofficeUserRole = func(id int64, value int64) error {
		return SetBackofficeUserRole(self.sandbox, &self, id, value)
	}
	self.RemoveBackofficeUser = func(id int64) error {
		return RemoveBackofficeUser(self.sandbox, &self, id)
	}
	self.AddBackofficeUserSession = func(parentId int64, props BackofficeUserSessionInput) (BackofficeUserSessionRecord, error) {
		return AddBackofficeUserSession(self.sandbox, &self, parentId, props)
	}
	self.ListBackofficeUserSessions = func(parentId int64) ([]BackofficeUserSessionRecord, error) {
		return ListBackofficeUserSessions(self.sandbox, &self, parentId)
	}
	self.AddApiToken = func(props ApiTokenInput) (ApiTokenRecord, error) {
		return AddApiToken(self.sandbox, &self, props)
	}
	self.FindApiTokenById = func(id int64) (ApiTokenRecord, bool) {
		return FindApiTokenById(self.sandbox, &self, id)
	}
	self.FindApiTokenByTokenSha256 = func(value string) (ApiTokenRecord, bool) {
		return FindApiTokenByTokenSha256(self.sandbox, &self, value)
	}
	self.ListApiTokens = func(filter ApiTokenFilter) ([]ApiTokenRecord, error) {
		return ListApiTokens(self.sandbox, &self, filter)
	}
	self.ListApiTokensPage = func(offset int, limit int) ([]ApiTokenRecord, error) {
		return ListApiTokensPage(self.sandbox, &self, offset, limit)
	}
	self.CountApiToken = func() (int, error) {
		return CountApiToken(self.sandbox, &self)
	}
	self.SetApiTokenTokenSha256 = func(id int64, value string) error {
		return SetApiTokenTokenSha256(self.sandbox, &self, id, value)
	}
	self.SetApiTokenName = func(id int64, value string) error {
		return SetApiTokenName(self.sandbox, &self, id, value)
	}
	self.SetApiTokenPrefix = func(id int64, value string) error {
		return SetApiTokenPrefix(self.sandbox, &self, id, value)
	}
	self.SetApiTokenOwnerId = func(id int64, value int64) error {
		return SetApiTokenOwnerId(self.sandbox, &self, id, value)
	}
	self.SetApiTokenCreatedAt = func(id int64, value int64) error {
		return SetApiTokenCreatedAt(self.sandbox, &self, id, value)
	}
	self.SetApiTokenExpiresAt = func(id int64, value int64) error {
		return SetApiTokenExpiresAt(self.sandbox, &self, id, value)
	}
	self.SetApiTokenIps = func(id int64, value string) error {
		return SetApiTokenIps(self.sandbox, &self, id, value)
	}
	self.SetApiTokenLastUsedAt = func(id int64, value int64) error {
		return SetApiTokenLastUsedAt(self.sandbox, &self, id, value)
	}
	self.SetApiTokenLastUsedIp = func(id int64, value string) error {
		return SetApiTokenLastUsedIp(self.sandbox, &self, id, value)
	}
	self.RemoveApiToken = func(id int64) error {
		return RemoveApiToken(self.sandbox, &self, id)
	}

	return &self
}
