// Code generated by agnos. DO NOT EDIT.

package backoffice_start_server

// Input is every value this command reads off a command line, one field per
// entry of its command.yaml: FullCommand, the whole command line, then one per
// entry of `args` and one per entry of `flags`, each tagged with the id the
// generic Run fills it by. Handle is handed one,
// already filled.
// Generated by `agnos build` — do not edit by hand.
type Input struct {
	FullCommand        []string `id:"FullCommand"`
	Verb               string   `id:"Verb"`
	Addr               string   `id:"Addr"`
	AllowXForwardedFor bool     `id:"AllowXForwardedFor"`
	InsecureHttp       bool     `id:"InsecureHttp"`
}
