package maindatabase

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
)

// This file is generated by `agnos build` from specs.yaml — do not edit by hand.
// A query specs.yaml cannot describe goes in methods_custom.go, which no build
// reads and no build rewrites.

// BackofficeuserItem is one stored backofficeuser record: its permanent id and every
// plain field the declaration gives it.
type BackofficeuserItem struct {
	Id          int64
	Username    string
	Email       string
	Passwordsha string
	Role        int64
}

// BackofficeuserNew is one insert into backofficeuser: the fields a new record carries.
type BackofficeuserNew struct {
	Username    string
	Email       string
	Passwordsha string
	Role        int64
}

// BackofficeuserFiltrage narrows a ListBackofficeuser. Every plain field is here, because
// only a `key` field is indexed and this is the one way to reach the rest. A
// zero value turns its own filter off.
type BackofficeuserFiltrage struct {
	UsernameStartsWith    string
	UsernameEquals        string
	EmailStartsWith       string
	EmailEquals           string
	PasswordshaStartsWith string
	PasswordshaEquals     string
	RoleMin               int64
	RoleMax               int64
}

// Maindatabase is the maindatabase database: the handle it was built over and one
// function field per generated method. Building one is free — it touches no
// key and creates nothing until the first record is written — so whoever needs
// it calls New on the spot instead of reading it off the Sandbox.
type Maindatabase struct {
	sandbox *api.Sandbox
	handle  database.DatabaseHandle

	// AddBackofficeuser inserts one backofficeuser record.
	AddBackofficeuser func(props BackofficeuserNew) (BackofficeuserItem, error)
	// FindBackofficeuserById reads one backofficeuser record by its permanent id.
	FindBackofficeuserById func(id int64) (BackofficeuserItem, bool)
	// ListBackofficeuser reads every backofficeuser record the filtrage keeps.
	ListBackofficeuser func(filtrage BackofficeuserFiltrage) ([]BackofficeuserItem, error)
	// PageBackofficeuser reads one page of backofficeuser records, counted from 1.
	PageBackofficeuser func(position int, chunk int) ([]BackofficeuserItem, error)
	// CountBackofficeuser is how many backofficeuser records are live.
	CountBackofficeuser func() (int, error)
	// UpdateBackofficeuserUsername writes a new username on one backofficeuser record.
	UpdateBackofficeuserUsername func(id int64, value string) error
	// UpdateBackofficeuserEmail writes a new email on one backofficeuser record.
	UpdateBackofficeuserEmail func(id int64, value string) error
	// UpdateBackofficeuserPasswordsha writes a new passwordsha on one backofficeuser record.
	UpdateBackofficeuserPasswordsha func(id int64, value string) error
	// UpdateBackofficeuserRole writes a new role on one backofficeuser record.
	UpdateBackofficeuserRole func(id int64, value int64) error
	// RemoveBackofficeuser deletes one backofficeuser record and everything nested under it.
	RemoveBackofficeuser func(id int64) error
}
