package maindatabase

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
	databaseio "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/generated/databaseio"
)

// This file is generated by `agnos build` from specs.yaml — do not edit by hand.
//
// Every function takes the sandbox first, the way every function of
// sandbox/internal/ does. A search answers (record, false) when there is
// nothing to find and a write answers an error when something went wrong; no
// stored value is ever asserted into a type without checking, so a malformed
// record is an error rather than a panic.

// AddBackofficeuser inserts one backofficeuser record.
func AddBackofficeuser(sandbox *api.Sandbox, self *Maindatabase, props BackofficeuserNew) (BackofficeuserItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return BackofficeuserItem{}, err
	}
	item, failure := schema.NewItem(newBackofficeuserFields(props))
	if failure != nil {
		return BackofficeuserItem{}, databaseio.Fail(sandbox, failure)
	}
	return buildBackofficeuserItem(sandbox, item)
}

// FindBackofficeuserById reads one backofficeuser record by its permanent id.
func FindBackofficeuserById(sandbox *api.Sandbox, self *Maindatabase, id int64) (BackofficeuserItem, bool) {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		sandbox.Deps.Std.Log("FindBackofficeuserById: %s \n", err.Error())
		return BackofficeuserItem{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return BackofficeuserItem{}, false
	}
	built, err := buildBackofficeuserItem(sandbox, item)
	if err != nil {
		sandbox.Deps.Std.Log("FindBackofficeuserById: %s \n", err.Error())
		return BackofficeuserItem{}, false
	}
	return built, true
}

// ListBackofficeuser reads every backofficeuser record the filtrage keeps.
func ListBackofficeuser(sandbox *api.Sandbox, self *Maindatabase, filtrage BackofficeuserFiltrage) ([]BackofficeuserItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return nil, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	kept := []BackofficeuserItem{}
	for _, item := range items {
		built, err := buildBackofficeuserItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		if !matchBackofficeuser(sandbox, built, filtrage) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
}

// PageBackofficeuser reads one page of backofficeuser records, counted from 1.
func PageBackofficeuser(sandbox *api.Sandbox, self *Maindatabase, position int, chunk int) ([]BackofficeuserItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return nil, err
	}
	items, failure := schema.List(position, chunk)
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	page := []BackofficeuserItem{}
	for _, item := range items {
		built, err := buildBackofficeuserItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
}

// CountBackofficeuser is how many backofficeuser records are live.
func CountBackofficeuser(sandbox *api.Sandbox, self *Maindatabase) (int, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return 0, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return 0, databaseio.Fail(sandbox, failure)
	}
	return len(items), nil
}

// UpdateBackofficeuserUsername writes a new username on one backofficeuser record.
func UpdateBackofficeuserUsername(sandbox *api.Sandbox, self *Maindatabase, id int64, value string) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("backofficeuser %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("username", value))
}

// UpdateBackofficeuserEmail writes a new email on one backofficeuser record.
func UpdateBackofficeuserEmail(sandbox *api.Sandbox, self *Maindatabase, id int64, value string) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("backofficeuser %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("email", value))
}

// UpdateBackofficeuserPasswordsha writes a new passwordsha on one backofficeuser record.
func UpdateBackofficeuserPasswordsha(sandbox *api.Sandbox, self *Maindatabase, id int64, value string) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("backofficeuser %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("passwordsha", value))
}

// UpdateBackofficeuserRole writes a new role on one backofficeuser record.
func UpdateBackofficeuserRole(sandbox *api.Sandbox, self *Maindatabase, id int64, value int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("backofficeuser %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("role", value))
}

// RemoveBackofficeuser deletes one backofficeuser record and everything nested under it.
func RemoveBackofficeuser(sandbox *api.Sandbox, self *Maindatabase, id int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "backofficeuser")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("backofficeuser %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Remove())
}

// newBackofficeuserFields is one insert into backofficeuser as the stored field map.
func newBackofficeuserFields(props BackofficeuserNew) map[string]any {
	return map[string]any{
		"username":    props.Username,
		"email":       props.Email,
		"passwordsha": props.Passwordsha,
		"role":        props.Role,
	}
}

// buildBackofficeuserItem reads one stored backofficeuser record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildBackofficeuserItem(sandbox *api.Sandbox, item database.SchemaItem) (BackofficeuserItem, error) {
	built := BackofficeuserItem{Id: item.Id}

	username_value, err := databaseio.ReadString(sandbox, item, "username")
	if err != nil {
		return built, err
	}
	built.Username = username_value

	email_value, err := databaseio.ReadString(sandbox, item, "email")
	if err != nil {
		return built, err
	}
	built.Email = email_value

	passwordsha_value, err := databaseio.ReadString(sandbox, item, "passwordsha")
	if err != nil {
		return built, err
	}
	built.Passwordsha = passwordsha_value

	role_value, err := databaseio.ReadInt(sandbox, item, "role")
	if err != nil {
		return built, err
	}
	built.Role = role_value

	return built, nil
}

// matchBackofficeuser is one BackofficeuserFiltrage applied to one record. A zero value
// never filters, so an empty filtrage keeps everything.
func matchBackofficeuser(sandbox *api.Sandbox, item BackofficeuserItem, filtrage BackofficeuserFiltrage) bool {
	if !databaseio.TextMatches(sandbox, item.Username, filtrage.UsernameStartsWith, filtrage.UsernameEquals) {
		return false
	}
	if !databaseio.TextMatches(sandbox, item.Email, filtrage.EmailStartsWith, filtrage.EmailEquals) {
		return false
	}
	if !databaseio.TextMatches(sandbox, item.Passwordsha, filtrage.PasswordshaStartsWith, filtrage.PasswordshaEquals) {
		return false
	}
	if !databaseio.IntInRange(item.Role, filtrage.RoleMin, filtrage.RoleMax) {
		return false
	}
	return true
}
