package maindatabase

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
)

// New builds the maindatabase database from the Props its specs.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a handle over a prefix, so building one creates nothing until the first
// record is written.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *Maindatabase {
	props := database.Props{
		Path:    "maindatabase",
		Schemas: []database.Schema{},
	}

	self := Maindatabase{sandbox: sandbox}
	self.handle = sandbox.Deps.Database.Databases.New(props)

	return &self
}
