package maindatabase

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
)

// New builds the maindatabase database from the Props its specs.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a handle over a prefix, so building one creates nothing until the first
// record is written.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *Maindatabase {
	props := database.Props{
		Path: "maindatabase",
		Schemas: []database.Schema{
			{
				Name: "backofficeuser",
				Itens: []database.Item{
					{Name: "username", Type: database.String, Required: true},
					{Name: "email", Type: database.String, Required: true},
					{Name: "passwordsha", Type: database.String, Required: true},
					{Name: "role", Type: database.Int},
					{Name: "sessions", Type: database.Database, Itens: []database.Item{
						{Name: "expiresat", Type: database.Int, Required: true}}},
				},
			},
		},
	}

	self := Maindatabase{sandbox: sandbox}
	self.handle = sandbox.Deps.Database.Databases.New(props)

	self.AddBackofficeuser = func(props BackofficeuserNew) (BackofficeuserItem, error) {
		return AddBackofficeuser(self.sandbox, &self, props)
	}
	self.FindBackofficeuserById = func(id int64) (BackofficeuserItem, bool) {
		return FindBackofficeuserById(self.sandbox, &self, id)
	}
	self.ListBackofficeuser = func(filtrage BackofficeuserFiltrage) ([]BackofficeuserItem, error) {
		return ListBackofficeuser(self.sandbox, &self, filtrage)
	}
	self.PageBackofficeuser = func(position int, chunk int) ([]BackofficeuserItem, error) {
		return PageBackofficeuser(self.sandbox, &self, position, chunk)
	}
	self.CountBackofficeuser = func() (int, error) {
		return CountBackofficeuser(self.sandbox, &self)
	}
	self.UpdateBackofficeuserUsername = func(id int64, value string) error {
		return UpdateBackofficeuserUsername(self.sandbox, &self, id, value)
	}
	self.UpdateBackofficeuserEmail = func(id int64, value string) error {
		return UpdateBackofficeuserEmail(self.sandbox, &self, id, value)
	}
	self.UpdateBackofficeuserPasswordsha = func(id int64, value string) error {
		return UpdateBackofficeuserPasswordsha(self.sandbox, &self, id, value)
	}
	self.UpdateBackofficeuserRole = func(id int64, value int64) error {
		return UpdateBackofficeuserRole(self.sandbox, &self, id, value)
	}
	self.RemoveBackofficeuser = func(id int64) error {
		return RemoveBackofficeuser(self.sandbox, &self, id)
	}
	self.AddBackofficeuserSessions = func(parent_id int64, props SessionsNew) (SessionsItem, error) {
		return AddBackofficeuserSessions(self.sandbox, &self, parent_id, props)
	}
	self.ListBackofficeuserSessions = func(parent_id int64) ([]SessionsItem, error) {
		return ListBackofficeuserSessions(self.sandbox, &self, parent_id)
	}

	return &self
}
