package help

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "help"
	command.Identifiers = []string{"help", "--help"}
	command.Category = "Info"
	command.Help = "Display help for a command"
	command.LongDescription = "When called without arguments, lists every available command\ngrouped by category. When called with a command name, shows\ndetailed usage, arguments, flags, and examples for that command.\n"
	command.Examples = []string{"help", "help start"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{}

	command.Args = []api.CommandArg{
		{
			Id:          "command",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "The command to describe; omit it to list every command",
			Examples:    []string{"help start"},
			Default:     "",
			HasDefault:  false,
		},
	}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
