package server

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	routeio "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeio"
	routeslist_health "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeslist/health"
	routeslist_home "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeslist/home"
	routeslist_not_found "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeslist/not_found"
	routeslist_test_middle "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeslist/test_middle"
	errors "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/server/errors"
)

// NewServer builds the http surface of the sandbox: Routes, one entry per
// sandbox/internal/routeslist/<name>/ built by that package's generated
// NewRoute — in run order, the lowest `priority` first and by name within one
// rung — Serve, the dispatch that reads a request against them, and Fail,
// which hands one failure to the project's own handler for it. Generated by
// `agnos build` — do not edit by hand.
func NewServer(sandbox *api.Sandbox) api.Server {
	server := api.Server{}

	server.Routes = []*api.Route{
		routeslist_home.NewRoute(sandbox),
		routeslist_test_middle.NewRoute(sandbox),
		routeslist_health.NewRoute(sandbox),
		routeslist_not_found.NewRoute(sandbox),
	}

	server.Serve = func(props api.ServeProps) error {
		return ServerMain(sandbox, props)
	}

	// One failure, one file of sandbox/internal/server/errors/. The switch is
	// the whole of the routing: every Handle* below is written once by
	// `agnos server-init` and is the project's from then on, so
	// changing what a 404 looks like is editing handle_not_found.go and
	// nothing else.
	//
	// A Handle* answers a failure; it never raises one. Calling routeio.Fail
	// from inside one comes back here and runs it again.
	server.Fail = func(route *api.Route) error {
		response := routeio.ResponseOf(route)

		if route.Failure != nil {
			switch route.Failure.Status {
			case api.StatusNotFound:
				return errors.HandleNotFound(sandbox, route, response)
			case api.StatusMethodNotAllowed:
				return errors.HandleMethodNotAllowed(sandbox, route, response)
			case api.StatusBadRequest:
				return errors.HandleBadRequest(sandbox, route, response)
			case api.StatusUnauthorized:
				return errors.HandleUnauthorized(sandbox, route, response)
			case api.StatusForbidden:
				return errors.HandleForbidden(sandbox, route, response)
			case api.StatusPayloadTooLarge:
				return errors.HandleTooLarge(sandbox, route, response)
			case api.StatusUnsupportedMedia:
				return errors.HandleWrongContentType(sandbox, route, response)
			}
		}

		return errors.HandleServerError(sandbox, route, response)
	}

	return server
}
