package finance

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
)

// This file is generated by `agnos build` from specs.yaml — do not edit by hand.
// A query specs.yaml cannot describe goes in methods_custom.go, which no build
// reads and no build rewrites.

// TransactionsItem is one stored transactions record: its permanent id and every
// plain field the declaration gives it.
type TransactionsItem struct {
	Id          int64
	Amount      float64
	Description string
	Type        string
	Date        string
}

// TransactionsNew is one insert into transactions: the fields a new record carries.
type TransactionsNew struct {
	Amount      float64
	Description string
	Type        string
	Date        string
}

// TransactionsFiltrage narrows a ListTransactions. Every plain field is here, because
// only a `key` field is indexed and this is the one way to reach the rest. A
// zero value turns its own filter off.
type TransactionsFiltrage struct {
	AmountMin             float64
	AmountMax             float64
	DescriptionStartsWith string
	DescriptionEquals     string
	TypeStartsWith        string
	TypeEquals            string
	DateStartsWith        string
	DateEquals            string
}

// Finance is the finance database: the handle it was built over and one
// function field per generated method. Building one is free — it touches no
// key and creates nothing until the first record is written — so whoever needs
// it calls New on the spot instead of reading it off the Sandbox.
type Finance struct {
	sandbox *api.Sandbox
	handle  database.DatabaseHandle

	// AddTransactions inserts one transactions record.
	AddTransactions func(props TransactionsNew) (TransactionsItem, error)
	// FindTransactionsById reads one transactions record by its permanent id.
	FindTransactionsById func(id int64) (TransactionsItem, bool)
	// ListTransactions reads every transactions record the filtrage keeps.
	ListTransactions func(filtrage TransactionsFiltrage) ([]TransactionsItem, error)
	// PageTransactions reads one page of transactions records, counted from 1.
	PageTransactions func(position int, chunk int) ([]TransactionsItem, error)
	// CountTransactions is how many transactions records are live.
	CountTransactions func() (int, error)
	// UpdateTransactionsAmount writes a new amount on one transactions record.
	UpdateTransactionsAmount func(id int64, value float64) error
	// UpdateTransactionsDescription writes a new description on one transactions record.
	UpdateTransactionsDescription func(id int64, value string) error
	// UpdateTransactionsType writes a new type on one transactions record.
	UpdateTransactionsType func(id int64, value string) error
	// UpdateTransactionsDate writes a new date on one transactions record.
	UpdateTransactionsDate func(id int64, value string) error
	// RemoveTransactions deletes one transactions record and everything nested under it.
	RemoveTransactions func(id int64) error
}
