package finance

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
	databaseio "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/databaseio"
)

// This file is generated by `agnos build` from specs.yaml — do not edit by hand.
//
// Every function takes the sandbox first, the way every function of
// sandbox/internal/ does. A search answers (record, false) when there is
// nothing to find and a write answers an error when something went wrong; no
// stored value is ever asserted into a type without checking, so a malformed
// record is an error rather than a panic.

// AddTransactions inserts one transactions record.
func AddTransactions(sandbox *api.Sandbox, self *Finance, props TransactionsNew) (TransactionsItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return TransactionsItem{}, err
	}
	item, failure := schema.NewItem(newTransactionsFields(props))
	if failure != nil {
		return TransactionsItem{}, databaseio.Fail(sandbox, failure)
	}
	return buildTransactionsItem(sandbox, item)
}

// FindTransactionsById reads one transactions record by its permanent id.
func FindTransactionsById(sandbox *api.Sandbox, self *Finance, id int64) (TransactionsItem, bool) {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		sandbox.Deps.Std.Log("FindTransactionsById: %s \n", err.Error())
		return TransactionsItem{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return TransactionsItem{}, false
	}
	built, err := buildTransactionsItem(sandbox, item)
	if err != nil {
		sandbox.Deps.Std.Log("FindTransactionsById: %s \n", err.Error())
		return TransactionsItem{}, false
	}
	return built, true
}

// ListTransactions reads every transactions record the filtrage keeps.
func ListTransactions(sandbox *api.Sandbox, self *Finance, filtrage TransactionsFiltrage) ([]TransactionsItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return nil, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	kept := []TransactionsItem{}
	for _, item := range items {
		built, err := buildTransactionsItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		if !matchTransactions(sandbox, built, filtrage) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
}

// PageTransactions reads one page of transactions records, counted from 1.
func PageTransactions(sandbox *api.Sandbox, self *Finance, position int, chunk int) ([]TransactionsItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return nil, err
	}
	items, failure := schema.List(position, chunk)
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	page := []TransactionsItem{}
	for _, item := range items {
		built, err := buildTransactionsItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
}

// CountTransactions is how many transactions records are live.
func CountTransactions(sandbox *api.Sandbox, self *Finance) (int, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return 0, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return 0, databaseio.Fail(sandbox, failure)
	}
	return len(items), nil
}

// UpdateTransactionsAmount writes a new amount on one transactions record.
func UpdateTransactionsAmount(sandbox *api.Sandbox, self *Finance, id int64, value float64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("transactions %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("amount", value))
}

// UpdateTransactionsDescription writes a new description on one transactions record.
func UpdateTransactionsDescription(sandbox *api.Sandbox, self *Finance, id int64, value string) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("transactions %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("description", value))
}

// UpdateTransactionsType writes a new type on one transactions record.
func UpdateTransactionsType(sandbox *api.Sandbox, self *Finance, id int64, value string) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("transactions %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("type", value))
}

// UpdateTransactionsDate writes a new date on one transactions record.
func UpdateTransactionsDate(sandbox *api.Sandbox, self *Finance, id int64, value string) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("transactions %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("date", value))
}

// RemoveTransactions deletes one transactions record and everything nested under it.
func RemoveTransactions(sandbox *api.Sandbox, self *Finance, id int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "transactions")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("transactions %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Remove())
}

// newTransactionsFields is one insert into transactions as the stored field map.
func newTransactionsFields(props TransactionsNew) map[string]any {
	return map[string]any{
		"amount":      props.Amount,
		"description": props.Description,
		"type":        props.Type,
		"date":        props.Date,
	}
}

// buildTransactionsItem reads one stored transactions record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildTransactionsItem(sandbox *api.Sandbox, item database.SchemaItem) (TransactionsItem, error) {
	built := TransactionsItem{Id: item.Id}

	amount_value, err := databaseio.ReadFloat(sandbox, item, "amount")
	if err != nil {
		return built, err
	}
	built.Amount = amount_value

	description_value, err := databaseio.ReadString(sandbox, item, "description")
	if err != nil {
		return built, err
	}
	built.Description = description_value

	type_value, err := databaseio.ReadString(sandbox, item, "type")
	if err != nil {
		return built, err
	}
	built.Type = type_value

	date_value, err := databaseio.ReadString(sandbox, item, "date")
	if err != nil {
		return built, err
	}
	built.Date = date_value

	return built, nil
}

// matchTransactions is one TransactionsFiltrage applied to one record. A zero value
// never filters, so an empty filtrage keeps everything.
func matchTransactions(sandbox *api.Sandbox, item TransactionsItem, filtrage TransactionsFiltrage) bool {
	if !databaseio.FloatInRange(item.Amount, filtrage.AmountMin, filtrage.AmountMax) {
		return false
	}
	if !databaseio.TextMatches(sandbox, item.Description, filtrage.DescriptionStartsWith, filtrage.DescriptionEquals) {
		return false
	}
	if !databaseio.TextMatches(sandbox, item.Type, filtrage.TypeStartsWith, filtrage.TypeEquals) {
		return false
	}
	if !databaseio.TextMatches(sandbox, item.Date, filtrage.DateStartsWith, filtrage.DateEquals) {
		return false
	}
	return true
}
