package finance

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	database "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/database"
)

// New builds the finance database from the Props its specs.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a handle over a prefix, so building one creates nothing until the first
// record is written.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *Finance {
	props := database.Props{
		Path: "finance",
		Schemas: []database.Schema{
			{
				Name: "transactions",
				Itens: []database.Item{
					{Name: "amount", Type: database.Float},
					{Name: "description", Type: database.String},
					{Name: "type", Type: database.String},
					{Name: "date", Type: database.String},
				},
			},
		},
	}

	self := Finance{sandbox: sandbox}
	self.handle = sandbox.Deps.Database.Databases.New(props)

	self.AddTransactions = func(props TransactionsNew) (TransactionsItem, error) {
		return AddTransactions(self.sandbox, &self, props)
	}
	self.FindTransactionsById = func(id int64) (TransactionsItem, bool) {
		return FindTransactionsById(self.sandbox, &self, id)
	}
	self.ListTransactions = func(filtrage TransactionsFiltrage) ([]TransactionsItem, error) {
		return ListTransactions(self.sandbox, &self, filtrage)
	}
	self.PageTransactions = func(position int, chunk int) ([]TransactionsItem, error) {
		return PageTransactions(self.sandbox, &self, position, chunk)
	}
	self.CountTransactions = func() (int, error) {
		return CountTransactions(self.sandbox, &self)
	}
	self.UpdateTransactionsAmount = func(id int64, value float64) error {
		return UpdateTransactionsAmount(self.sandbox, &self, id, value)
	}
	self.UpdateTransactionsDescription = func(id int64, value string) error {
		return UpdateTransactionsDescription(self.sandbox, &self, id, value)
	}
	self.UpdateTransactionsType = func(id int64, value string) error {
		return UpdateTransactionsType(self.sandbox, &self, id, value)
	}
	self.UpdateTransactionsDate = func(id int64, value string) error {
		return UpdateTransactionsDate(self.sandbox, &self, id, value)
	}
	self.RemoveTransactions = func(id int64) error {
		return RemoveTransactions(self.sandbox, &self, id)
	}

	return &self
}
