package static

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeio"
)

// NewRoute builds this route's declaration — the whole of what its route.yaml
// says — and closes RouteHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) api.Route {
	route := api.NewRoute()

	route.Name = "static"
	route.Method = "GET"
	route.Pattern = "/static/{item...}"
	route.Category = "Assets"
	route.Help = "Serves one file from the embedded static assets"
	route.LongDescription = ""
	route.Examples = []string{}
	route.Hidden = false

	route.Paths = []api.RoutePath{
		{
			Identifier: "/static",
		},
		{
			Field: &api.RouteField{
				Id:          "item",
				Type:        "string",
				Required:    true,
				Array:       true,
				Description: "the asset path under assets/frontend/static, one or more segments",
				Examples:    []string{},
				Default:     "",
				HasDefault:  false,
			},
		},
	}

	route.Headers = []api.RouteField{}

	route.Params = []api.RouteField{
		{
			Id:          "sha",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the digest staticref stamped on the url; when it matches the asset the answer is cacheable forever",
			Examples:    []string{},
			Default:     "",
			HasDefault:  false,
		},
	}

	route.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	route.Handler = func(bound *api.Route) int {
		return RouteHandler(sandbox, bound, routeio.ResponseOf(bound))
	}

	return *route
}
