// Code generated by agnos. DO NOT EDIT.

package config

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
)

// NewConfig builds Sandbox.Config out of what AgnosConfig/project.yaml
// declared when this file was rendered, so nothing has to parse that file to
// know which project it is running as. Every database lives under
// api.DefaultDatabaseDir until a command line's --database says otherwise.
// Generated by `agnos build` — do not edit by hand.
func NewConfig(sandbox *api.Sandbox) api.Config {
	return api.Config{
		ProjectName:    "testebackoffice",
		Version:        "",
		DatabaseConfig: api.DatabaseConfig{DatabaseDir: api.DefaultDatabaseDir},
	}
}
