package autentication

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/generated/server/route"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/generated/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "autentication"
	self.AcceptMethods = []string{"ANY"}
	self.Priority = 10
	self.ResponseType = "text/html"
	self.Segments = 0
	self.Pattern = "/admin/* !(/admin/login)"
	self.Category = "Middleware"
	self.Help = "Requires a valid backoffice session on /admin, except /admin/login"
	self.LongDescription = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Admin",
			Start:       0,
			End:         -1,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.PrefixTrigger, Value: "/admin", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "NotLogin",
			Start:       0,
			End:         -1,
			Type:        api.StringPath,
			Description: "the login route is reachable without a session",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "/admin/login", Negate: true, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "AdminToken",
			Key:         "admin_token",
			Fonts:       []api.ParameterFont{api.CookieParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the session JWT set by POST /admin/login",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "XClientIp",
			Key:         "x-client-ip",
			Fonts:       []api.ParameterFont{api.HeaderParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the ip the request came from, set by the server and never by the client",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
