package health

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "health"
	self.Methods = []string{"GET"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 0
	self.Pattern = "/health"
	self.Category = "Server"
	self.Summary = "Reports that the server is up"
	self.Description = ""
	self.Examples = []string{"curl localhost:3000/health"}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Health",
			Start:       0,
			End:         -1,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/health", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
