// Code generated by agnos. DO NOT EDIT.

package api_list_backups

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/generated.new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "api_list_backups"
	self.Methods = []string{"GET"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 4
	self.Pattern = "/api/admin/root/list-backups"
	self.Category = "Backoffice Backups API"
	self.Summary = "Lists every snapshot, or the ones whose name starts with a prefix, newest first, and whether a backup job is running"
	self.Description = ""
	self.Examples = []string{"curl localhost:3000/api/admin/root/list-backups -H \"Authorization: Bearer $TOKEN\"", "curl \"localhost:3000/api/admin/root/list-backups?prefix=daily-\" -H \"Authorization: Bearer $TOKEN\""}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "ApiAdminRootListBackups",
			Start:       0,
			End:         3,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/api/admin/root/list-backups", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "Prefix",
			Key:         "prefix",
			Sources:     []api.ParameterSource{api.SourceQuery},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "keeps only the snapshots whose name starts with it",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
