// Code generated by agnos. DO NOT EDIT.

package upload_backup

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
)

// Input is every value this route reads off a request, one field per entry
// of its route.yaml: FullRoute, the whole request path, then one per entry of
// `paths` and one per entry of `parameters`, then Body when the route declares
// one, each tagged with the id the generic Run fills it by. Handle is handed
// one, already filled.
// Generated by `agnos build` — do not edit by hand.
type Input struct {
	FullRoute             string `id:"FullRoute"`
	AdminRootUploadBackup string `id:"AdminRootUploadBackup"`
	Body                  []byte `id:"Body"`
}

// MaxBodyBytes is the largest request body this route reads, from the
// `max-bytes` of its declaration. A longer one is answered 413.
const MaxBodyBytes = 268435456

// ReadBody reads, validates and converts the request body of one bound route.
// The generic Run calls it — through the ReadBody generated.new.go closes over
// the sandbox — before Handle runs, and binds what it returns onto
// Input.Body; a middleware in front of this route may still refuse a request
// before a byte of it is read.
//
// It returns nil when the body passed. Any other failure comes back built by
// Deps.OpinionatedAgnosServer.Fail, which the lib's dispatch raises — reaching
// this project's own HandleBadRequest or HandlePayloadTooLarge — and the handler never
// runs.
func ReadBody(sandbox *api.Sandbox, route *api.Route) ([]byte, error) {
	var body []byte

	raw, err := route.Request.ReadBody(MaxBodyBytes)
	if err != nil {
		return body, sandbox.Deps.OpinionatedAgnosServer.FailWithCause(api.StatusPayloadTooLarge, "",
			"the request body is larger than 268435456 bytes", err.Error())
	}

	if len(raw) == 0 {
		return body, sandbox.Deps.OpinionatedAgnosServer.Fail(api.StatusBadRequest, "",
			"this route requires a request body")
	}

	body = raw

	return body, nil
}
