package backoffice_client_ip

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "backoffice_client_ip"
	self.Methods = []string{"ANY"}
	self.Priority = 7
	self.ResponseType = "text/plain"
	self.Segments = 0
	self.Pattern = "/*"
	self.Category = "Middleware"
	self.Summary = "Works out the client ip every route after it reads, from the connection or the reverse proxy in front"
	self.Description = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Root",
			Start:       0,
			End:         -1,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerPrefix, Value: "/", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "XClientIp",
			Key:         "x-client-ip",
			Sources:     []api.ParameterSource{api.SourceHeader},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "the ip of the connection, set by the server and never by the client",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "XForwardedFor",
			Key:         "x-forwarded-for",
			Sources:     []api.ParameterSource{api.SourceHeader},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "the client chain a reverse proxy appended to, read only with --allow-x-forwarded-for",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
