package version

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/generated/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "version"
	command.Identifiers = []string{"version", "--version"}
	command.Category = "Info"
	command.Help = "Print the installed version"
	command.LongDescription = "Prints the current version of the installed binary and exits.\n"
	command.Examples = []string{"version"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{}

	command.Args = []api.CommandArg{}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
