// Code generated by agnos. DO NOT EDIT.

package api_upload_backup

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/generated.new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "api_upload_backup"
	self.Methods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 4
	self.Pattern = "/api/admin/root/upload-backup"
	self.Category = "Backoffice Backups API"
	self.Summary = "Stores a zip archive a download built as a new snapshot"
	self.Description = ""
	self.Examples = []string{"curl -X POST localhost:3000/api/admin/root/upload-backup -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/zip' --data-binary @snapshot.zip"}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "ApiAdminRootUploadBackup",
			Start:       0,
			End:         3,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/api/admin/root/upload-backup", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "raw",
		Required:    true,
		MaxBytes:    268435456,
		ContentType: "application/zip",
		Schema:      "",
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
