package databasedeps

import (
	remotebinding "github.com/MateusMoutinhoOrg/Keep/adapters/bindings/standard"
	remotelib "github.com/MateusMoutinhoOrg/Keep/sandbox"
	remoteapi "github.com/MateusMoutinhoOrg/Keep/sandbox/api"

	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// Bind fills deps.DatabaseDeps with github.com/MateusMoutinhoOrg/Keep, built from that repo's own
// adapters and handed over as the copy of its contract this project carries in
// sandbox/deps/databasedeps.
//
// This file is generated by `agnos add-dep github.com/MateusMoutinhoOrg/Keep` and rewritten by
// `agnos set-dep databasedeps`. The conversion below cannot live in the remote repo:
// databasedeps.Sandbox has an import path inside this module, which that repo does not
// know when it publishes, and a top-level cast will not stand in for it —
// Go's type identity does not reach through named types, so two copies of a
// struct whose fields are named types are never the same type.
func Bind(deps *deps.Deps) {
	remote_deps := remotebinding.New()
	remote_sandbox := remotelib.New(&remote_deps)
	deps.DatabaseDeps = convSandbox(*remote_sandbox)
}

// convSandbox carries one value between the two copies of the contract.
func convSandbox(v remoteapi.Sandbox) databasedeps.Sandbox {
	return databasedeps.Sandbox{
		ProjectSandbox: convProjectSandbox(v.ProjectSandbox),
		Config:         convConfig(v.Config),
	}
}

// convProjectSandbox carries one value between the two copies of the contract.
func convProjectSandbox(v remoteapi.ProjectSandbox) databasedeps.ProjectSandbox {
	return databasedeps.ProjectSandbox{
		Databases: convDatabases(v.Databases),
		Info:      convInfo(v.Info),
	}
}

// convDatabases carries one value between the two copies of the contract.
func convDatabases(v remoteapi.Databases) databasedeps.Databases {
	return databasedeps.Databases{
		New: func(p0 databasedeps.Props) (databasedeps.Database, *databasedeps.Error) {
			r0, r1 := v.New(revProps(p0))
			return convDatabase(r0), convPtrError(r1)
		},
	}
}

// revProps carries one value between the two copies of the contract.
func revProps(v databasedeps.Props) remoteapi.Props {
	return remoteapi.Props{
		Path:    v.Path,
		Schemas: revSliceSchema(v.Schemas),
	}
}

// revSliceSchema carries one value between the two copies of the contract.
func revSliceSchema(v []databasedeps.Schema) []remoteapi.Schema {
	if v == nil {
		return nil
	}

	out := make([]remoteapi.Schema, len(v))
	for index := range v {
		out[index] = revSchema(v[index])
	}

	return out
}

// revSchema carries one value between the two copies of the contract.
func revSchema(v databasedeps.Schema) remoteapi.Schema {
	return remoteapi.Schema{
		Name:   v.Name,
		Fields: revSliceField(v.Fields),
	}
}

// revSliceField carries one value between the two copies of the contract.
func revSliceField(v []databasedeps.Field) []remoteapi.Field {
	if v == nil {
		return nil
	}

	out := make([]remoteapi.Field, len(v))
	for index := range v {
		out[index] = revField(v[index])
	}

	return out
}

// revField carries one value between the two copies of the contract.
func revField(v databasedeps.Field) remoteapi.Field {
	return remoteapi.Field{
		Name:     v.Name,
		Type:     v.Type,
		Required: v.Required,
		Target:   v.Target,
		Fields:   revSliceField(v.Fields),
	}
}

// convDatabase carries one value between the two copies of the contract.
func convDatabase(v remoteapi.Database) databasedeps.Database {
	return databasedeps.Database{
		Props: convProps(v.Props),
		Collection: func(p0 string) (databasedeps.Collection, bool) {
			r0, r1 := v.Collection(p0)
			return convCollection(r0), r1
		},
	}
}

// convProps carries one value between the two copies of the contract.
func convProps(v remoteapi.Props) databasedeps.Props {
	return databasedeps.Props{
		Path:    v.Path,
		Schemas: convSliceSchema(v.Schemas),
	}
}

// convSliceSchema carries one value between the two copies of the contract.
func convSliceSchema(v []remoteapi.Schema) []databasedeps.Schema {
	if v == nil {
		return nil
	}

	out := make([]databasedeps.Schema, len(v))
	for index := range v {
		out[index] = convSchema(v[index])
	}

	return out
}

// convSchema carries one value between the two copies of the contract.
func convSchema(v remoteapi.Schema) databasedeps.Schema {
	return databasedeps.Schema{
		Name:   v.Name,
		Fields: convSliceField(v.Fields),
	}
}

// convSliceField carries one value between the two copies of the contract.
func convSliceField(v []remoteapi.Field) []databasedeps.Field {
	if v == nil {
		return nil
	}

	out := make([]databasedeps.Field, len(v))
	for index := range v {
		out[index] = convField(v[index])
	}

	return out
}

// convField carries one value between the two copies of the contract.
func convField(v remoteapi.Field) databasedeps.Field {
	return databasedeps.Field{
		Name:     v.Name,
		Type:     v.Type,
		Required: v.Required,
		Target:   v.Target,
		Fields:   convSliceField(v.Fields),
	}
}

// convCollection carries one value between the two copies of the contract.
func convCollection(v remoteapi.Collection) databasedeps.Collection {
	return databasedeps.Collection{
		Fields: convSliceField(v.Fields),
		Prefix: v.Prefix,
		Insert: func(p0 map[string]any) (databasedeps.Record, *databasedeps.Error) {
			r0, r1 := v.Insert(p0)
			return convRecord(r0), convPtrError(r1)
		},
		FindByKey: func(p0 string, p1 any) (databasedeps.Record, bool, *databasedeps.Error) {
			r0, r1, r2 := v.FindByKey(p0, p1)
			return convRecord(r0), r1, convPtrError(r2)
		},
		FindByID: func(p0 int64) (databasedeps.Record, bool, *databasedeps.Error) {
			r0, r1, r2 := v.FindByID(p0)
			return convRecord(r0), r1, convPtrError(r2)
		},
		ListAll: func() ([]databasedeps.Record, *databasedeps.Error) {
			r0, r1 := v.ListAll()
			return convSliceRecord(r0), convPtrError(r1)
		},
		List: func(p0 int, p1 int) ([]databasedeps.Record, *databasedeps.Error) {
			r0, r1 := v.List(p0, p1)
			return convSliceRecord(r0), convPtrError(r1)
		},
		Repair: func() *databasedeps.Error { return convPtrError(v.Repair()) },
	}
}

// convRecord carries one value between the two copies of the contract.
func convRecord(v remoteapi.Record) databasedeps.Record {
	return databasedeps.Record{
		Fields: convSliceField(v.Fields),
		Prefix: v.Prefix,
		ID:     v.ID,
		Get: func(p0 string) (any, *databasedeps.Error) {
			r0, r1 := v.Get(p0)
			return r0, convPtrError(r1)
		},
		GetLink: func(p0 string) (databasedeps.Record, bool, *databasedeps.Error) {
			r0, r1, r2 := v.GetLink(p0)
			return convRecord(r0), r1, convPtrError(r2)
		},
		Update: func(p0 string, p1 any) *databasedeps.Error { return convPtrError(v.Update(p0, p1)) },
		Remove: func() *databasedeps.Error { return convPtrError(v.Remove()) },
		HasValues: func(p0 []string) (bool, *databasedeps.Error) {
			r0, r1 := v.HasValues(p0)
			return r0, convPtrError(r1)
		},
		Nested: func(p0 string) (databasedeps.Collection, *databasedeps.Error) {
			r0, r1 := v.Nested(p0)
			return convCollection(r0), convPtrError(r1)
		},
		ListNested: func(p0 string) ([]databasedeps.Record, *databasedeps.Error) {
			r0, r1 := v.ListNested(p0)
			return convSliceRecord(r0), convPtrError(r1)
		},
		InsertNested: func(p0 string, p1 map[string]any) (databasedeps.Record, *databasedeps.Error) {
			r0, r1 := v.InsertNested(p0, p1)
			return convRecord(r0), convPtrError(r1)
		},
		String: v.String,
	}
}

// convPtrError carries one value between the two copies of the contract.
func convPtrError(v *remoteapi.Error) *databasedeps.Error {
	if v == nil {
		return nil
	}

	out := convError(*v)
	return &out
}

// convError carries one value between the two copies of the contract.
func convError(v remoteapi.Error) databasedeps.Error {
	return databasedeps.Error{
		Type:    v.Type,
		Field:   v.Field,
		Value:   v.Value,
		Message: v.Message,
	}
}

// convSliceRecord carries one value between the two copies of the contract.
func convSliceRecord(v []remoteapi.Record) []databasedeps.Record {
	if v == nil {
		return nil
	}

	out := make([]databasedeps.Record, len(v))
	for index := range v {
		out[index] = convRecord(v[index])
	}

	return out
}

// convInfo carries one value between the two copies of the contract.
func convInfo(v remoteapi.Info) databasedeps.Info {
	return databasedeps.Info{
		Name:    v.Name,
		Version: v.Version,
	}
}

// convConfig carries one value between the two copies of the contract.
func convConfig(v remoteapi.Config) databasedeps.Config {
	return databasedeps.Config{
		ProjectConfig: convProjectConfig(v.ProjectConfig),
		ProjectName:   v.ProjectName,
		Version:       v.Version,
	}
}

// convProjectConfig carries one value between the two copies of the contract.
func convProjectConfig(v remoteapi.ProjectConfig) databasedeps.ProjectConfig {
	return databasedeps.ProjectConfig{}
}
