package databasedeps

import (
	remotebinding "github.com/MateusMoutinhoOrg/Keep/adapters/availables/standard"
	remotelib "github.com/MateusMoutinhoOrg/Keep/sandbox"
	remoteapi "github.com/MateusMoutinhoOrg/Keep/sandbox/api"

	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// Bind fills deps.DatabaseDeps with github.com/MateusMoutinhoOrg/Keep, built from that repo's own
// adapters and handed over as the copy of its contract this project carries in
// sandbox/deps/databasedeps.
//
// This file is generated by `agnos add-dep github.com/MateusMoutinhoOrg/Keep` and rewritten by
// `agnos set-dep databasedeps`. The conversion below cannot live in the remote repo:
// databasedeps.Sandbox has an import path inside this module, which that repo does not
// know when it publishes, and a top-level cast will not stand in for it —
// Go's type identity does not reach through named types, so two copies of a
// struct whose fields are named types are never the same type.
func Bind(deps *deps.Deps) {
	remote_deps := remotebinding.New()
	remote_sandbox := remotelib.New(&remote_deps)
	deps.DatabaseDeps = convSandbox(*remote_sandbox)
}

// convSandbox carries one value between the two copies of the contract.
func convSandbox(v remoteapi.Sandbox) databasedeps.Sandbox {
	return databasedeps.Sandbox{
		Databases: convDatabases(v.Databases),
		Info:      convInfo(v.Info),
	}
}

// convDatabases carries one value between the two copies of the contract.
func convDatabases(v remoteapi.Databases) databasedeps.Databases {
	return databasedeps.Databases{
		New: func(p0 databasedeps.Props) databasedeps.DatabaseHandle {
			return convDatabaseHandle(v.New(revProps(p0)))
		},
	}
}

// revProps carries one value between the two copies of the contract.
func revProps(v databasedeps.Props) remoteapi.Props {
	return remoteapi.Props{
		Path:    v.Path,
		Schemas: revSliceSchema(v.Schemas),
	}
}

// revSliceSchema carries one value between the two copies of the contract.
func revSliceSchema(v []databasedeps.Schema) []remoteapi.Schema {
	if v == nil {
		return nil
	}

	out := make([]remoteapi.Schema, len(v))
	for index := range v {
		out[index] = revSchema(v[index])
	}

	return out
}

// revSchema carries one value between the two copies of the contract.
func revSchema(v databasedeps.Schema) remoteapi.Schema {
	return remoteapi.Schema{
		Name:  v.Name,
		Itens: revSliceItem(v.Itens),
	}
}

// revSliceItem carries one value between the two copies of the contract.
func revSliceItem(v []databasedeps.Item) []remoteapi.Item {
	if v == nil {
		return nil
	}

	out := make([]remoteapi.Item, len(v))
	for index := range v {
		out[index] = revItem(v[index])
	}

	return out
}

// revItem carries one value between the two copies of the contract.
func revItem(v databasedeps.Item) remoteapi.Item {
	return remoteapi.Item{
		Name:     v.Name,
		Type:     v.Type,
		Required: v.Required,
		Target:   v.Target,
		Itens:    revSliceItem(v.Itens),
	}
}

// convDatabaseHandle carries one value between the two copies of the contract.
func convDatabaseHandle(v remoteapi.DatabaseHandle) databasedeps.DatabaseHandle {
	return databasedeps.DatabaseHandle{
		Props: convProps(v.Props),
		GetSchema: func(p0 string) (databasedeps.SchemaInstance, bool) {
			r0, r1 := v.GetSchema(p0)
			return convSchemaInstance(r0), r1
		},
	}
}

// convProps carries one value between the two copies of the contract.
func convProps(v remoteapi.Props) databasedeps.Props {
	return databasedeps.Props{
		Path:    v.Path,
		Schemas: convSliceSchema(v.Schemas),
	}
}

// convSliceSchema carries one value between the two copies of the contract.
func convSliceSchema(v []remoteapi.Schema) []databasedeps.Schema {
	if v == nil {
		return nil
	}

	out := make([]databasedeps.Schema, len(v))
	for index := range v {
		out[index] = convSchema(v[index])
	}

	return out
}

// convSchema carries one value between the two copies of the contract.
func convSchema(v remoteapi.Schema) databasedeps.Schema {
	return databasedeps.Schema{
		Name:  v.Name,
		Itens: convSliceItem(v.Itens),
	}
}

// convSliceItem carries one value between the two copies of the contract.
func convSliceItem(v []remoteapi.Item) []databasedeps.Item {
	if v == nil {
		return nil
	}

	out := make([]databasedeps.Item, len(v))
	for index := range v {
		out[index] = convItem(v[index])
	}

	return out
}

// convItem carries one value between the two copies of the contract.
func convItem(v remoteapi.Item) databasedeps.Item {
	return databasedeps.Item{
		Name:     v.Name,
		Type:     v.Type,
		Required: v.Required,
		Target:   v.Target,
		Itens:    convSliceItem(v.Itens),
	}
}

// convSchemaInstance carries one value between the two copies of the contract.
func convSchemaInstance(v remoteapi.SchemaInstance) databasedeps.SchemaInstance {
	return databasedeps.SchemaInstance{
		Items:  convSliceItem(v.Items),
		Prefix: v.Prefix,
		NewItem: func(p0 map[string]any) (databasedeps.SchemaItem, *databasedeps.Error) {
			r0, r1 := v.NewItem(p0)
			return convSchemaItem(r0), convPtrError(r1)
		},
		FindByKey: func(p0 string, p1 any) (databasedeps.SchemaItem, bool) {
			r0, r1 := v.FindByKey(p0, p1)
			return convSchemaItem(r0), r1
		},
		FindById: func(p0 int64) (databasedeps.SchemaItem, bool) {
			r0, r1 := v.FindById(p0)
			return convSchemaItem(r0), r1
		},
		ListAll: func() ([]databasedeps.SchemaItem, *databasedeps.Error) {
			r0, r1 := v.ListAll()
			return convSliceSchemaItem(r0), convPtrError(r1)
		},
		List: func(p0 int, p1 int) ([]databasedeps.SchemaItem, *databasedeps.Error) {
			r0, r1 := v.List(p0, p1)
			return convSliceSchemaItem(r0), convPtrError(r1)
		},
	}
}

// convSchemaItem carries one value between the two copies of the contract.
func convSchemaItem(v remoteapi.SchemaItem) databasedeps.SchemaItem {
	return databasedeps.SchemaItem{
		Items:  convSliceItem(v.Items),
		Prefix: v.Prefix,
		Id:     v.Id,
		Get: func(p0 string) (any, *databasedeps.Error) {
			r0, r1 := v.Get(p0)
			return r0, convPtrError(r1)
		},
		GetLink: func(p0 string) (databasedeps.SchemaItem, bool) {
			r0, r1 := v.GetLink(p0)
			return convSchemaItem(r0), r1
		},
		Update:            func(p0 string, p1 any) *databasedeps.Error { return convPtrError(v.Update(p0, p1)) },
		Remove:            func() *databasedeps.Error { return convPtrError(v.Remove()) },
		CheckKeysPresence: v.CheckKeysPresence,
		ListAll:           func(p0 string) []databasedeps.SchemaItem { return convSliceSchemaItem(v.ListAll(p0)) },
		NewSubItem: func(p0 string, p1 map[string]any) (databasedeps.SchemaItem, *databasedeps.Error) {
			r0, r1 := v.NewSubItem(p0, p1)
			return convSchemaItem(r0), convPtrError(r1)
		},
		String: v.String,
	}
}

// convPtrError carries one value between the two copies of the contract.
func convPtrError(v *remoteapi.Error) *databasedeps.Error {
	if v == nil {
		return nil
	}

	out := convError(*v)
	return &out
}

// convError carries one value between the two copies of the contract.
func convError(v remoteapi.Error) databasedeps.Error {
	return databasedeps.Error{
		Type:     v.Type,
		Key:      v.Key,
		KeyValue: v.KeyValue,
		Message:  v.Message,
	}
}

// convSliceSchemaItem carries one value between the two copies of the contract.
func convSliceSchemaItem(v []remoteapi.SchemaItem) []databasedeps.SchemaItem {
	if v == nil {
		return nil
	}

	out := make([]databasedeps.SchemaItem, len(v))
	for index := range v {
		out[index] = convSchemaItem(v[index])
	}

	return out
}

// convInfo carries one value between the two copies of the contract.
func convInfo(v remoteapi.Info) databasedeps.Info {
	return databasedeps.Info{
		Name:    v.Name,
		Version: v.Version,
	}
}
