package api_download_backup

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "api_download_backup"
	self.Methods = []string{"GET"}
	self.Priority = 100
	self.ResponseType = "application/zip"
	self.Segments = 5
	self.Pattern = "/api/admin/root/download-backup/{Id:integer}"
	self.Category = "Backoffice Backups API"
	self.Summary = "Downloads a snapshot as a zip archive"
	self.Description = ""
	self.Examples = []string{"curl -o snapshot.zip localhost:3000/api/admin/root/download-backup/1 -H \"Authorization: Bearer $TOKEN\""}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "ApiAdminRootDownloadBackup",
			Start:       0,
			End:         3,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/api/admin/root/download-backup", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Id",
			Start:       4,
			End:         4,
			Type:        api.PathInteger,
			Description: "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
