package api_remove_backoffice_user

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinatedAgnosServer.NewRoute, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinatedAgnosServer.NewRoute()

	self.Name = "api_remove_backoffice_user"
	self.AcceptMethods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 4
	self.Pattern = "/api/admin/root/remove-backoffice-user"
	self.Category = "Backoffice Users API"
	self.Help = "Removes a backoffice user and every session of it"
	self.LongDescription = ""
	self.Examples = []string{"curl -X POST localhost:3000/api/admin/root/remove-backoffice-user -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' -d '{\"id\":2}'"}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "ApiAdminRootRemoveBackofficeUser",
			Start:       0,
			End:         3,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "/api/admin/root/remove-backoffice-user", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "json",
		Required:    true,
		MaxBytes:    1048576,
		ContentType: "application/json",
		Schema:      BodySchema,
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
