// Code generated by agnos. DO NOT EDIT.

package front

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/generated.new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "front"
	self.Methods = []string{"GET"}
	self.Priority = 1000
	self.ResponseType = "text/html; charset=utf-8"
	self.Segments = 0
	self.Pattern = "/{*Rest}"
	self.Category = "Assets"
	self.Summary = "Serves any file of the embedded assets/front tree"
	self.Description = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Rest",
			Start:       0,
			End:         -1,
			Type:        api.PathString,
			Description: "the file under assets/front; none is its index.html",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
