// Code generated by agnos. DO NOT EDIT.

package api_restore_backup

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/generated.new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "api_restore_backup"
	self.Methods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 4
	self.Pattern = "/api/admin/root/restore-backup"
	self.Category = "Backoffice Backups API"
	self.Summary = "Starts putting a snapshot back over every database, after a pre-restore snapshot of them, and answers 202 at once"
	self.Description = "The backoffice's own users, sessions and API tokens (backofficedb) are kept as they are unless include-backoffice is true: an older copy would bring back revoked tokens, closed sessions, removed users and old passwords. A restore that fails, or that the process stopped in the middle of, puts the pre-restore snapshot back; every request is answered 503 while it runs."
	self.Examples = []string{"curl -X POST localhost:3000/api/admin/root/restore-backup -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' -d '{\"id\":1,\"include-backoffice\":false}'"}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "ApiAdminRootRestoreBackup",
			Start:       0,
			End:         3,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/api/admin/root/restore-backup", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "json",
		Required:    true,
		MaxBytes:    4096,
		ContentType: "application/json",
		Schema:      BodySchema,
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
