package backup

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// This file is generated by `agnos build` from database.yaml — do not edit by hand.
// A query database.yaml cannot describe goes in methods_custom.go, which no build
// reads and no build rewrites.

// Backup is the backup database: the handle it was built over and one
// function field per generated method. Building one is free — it touches no
// key and creates nothing until the first record is written — so whoever needs
// it calls New on the spot instead of reading it off the Sandbox.
type Backup struct {
	sandbox *api.Sandbox
	handle  databasedeps.DatabaseHandle
}
