package backup

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// This file is generated by `agnos build` from database.yaml — do not edit by hand.
//
// Every function takes the sandbox first, the way every function of
// sandbox/internal/ does. A search answers (record, false) when there is
// nothing to find and a write answers an error when something went wrong; no
// stored value is ever asserted into a type without checking, so a malformed
// record is an error rather than a panic.

// AddBlob inserts one blob record.
func AddBlob(sandbox *api.Sandbox, self *Backup, props BlobInput) (BlobRecord, error) {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		return BlobRecord{}, err
	}
	record, failure := collection.Insert(newBlobFields(props))
	if failure != nil {
		return BlobRecord{}, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return buildBlobRecord(sandbox, record)
}

// FindBlobById reads one blob record by its permanent id.
func FindBlobById(sandbox *api.Sandbox, self *Backup, id int64) (BlobRecord, bool) {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindBlobById: %s \n", err.Error())
		return BlobRecord{}, false
	}
	record, ok, failure := collection.FindByID(id)
	if failure != nil {
		sandbox.Deps.StdDeps.Logf("FindBlobById: %s \n", sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure).Error())
		return BlobRecord{}, false
	}
	if !ok {
		return BlobRecord{}, false
	}
	built, err := buildBlobRecord(sandbox, record)
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindBlobById: %s \n", err.Error())
		return BlobRecord{}, false
	}
	return built, true
}

// FindBlobBySha reads one blob record by its indexed sha.
func FindBlobBySha(sandbox *api.Sandbox, self *Backup, value string) (BlobRecord, bool) {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindBlobBySha: %s \n", err.Error())
		return BlobRecord{}, false
	}
	record, ok, failure := collection.FindByKey("sha", value)
	if failure != nil {
		sandbox.Deps.StdDeps.Logf("FindBlobBySha: %s \n", sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure).Error())
		return BlobRecord{}, false
	}
	if !ok {
		return BlobRecord{}, false
	}
	built, err := buildBlobRecord(sandbox, record)
	if err != nil {
		sandbox.Deps.StdDeps.Logf("FindBlobBySha: %s \n", err.Error())
		return BlobRecord{}, false
	}
	return built, true
}

// ListBlobs reads every blob record the filter keeps.
func ListBlobs(sandbox *api.Sandbox, self *Backup, filter BlobFilter) ([]BlobRecord, error) {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		return nil, err
	}
	records, failure := collection.ListAll()
	if failure != nil {
		return nil, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	kept := []BlobRecord{}
	for _, record := range records {
		built, err := buildBlobRecord(sandbox, record)
		if err != nil {
			return nil, err
		}
		if !matchBlob(sandbox, built, filter) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
}

// ListBlobsPage reads up to limit blob records after the first offset, every one past them when limit is 0.
func ListBlobsPage(sandbox *api.Sandbox, self *Backup, offset int, limit int) ([]BlobRecord, error) {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		return nil, err
	}
	records, failure := collection.List(offset+1, limit)
	if failure != nil {
		return nil, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	page := []BlobRecord{}
	for _, record := range records {
		built, err := buildBlobRecord(sandbox, record)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
}

// CountBlob is how many blob records are live.
func CountBlob(sandbox *api.Sandbox, self *Backup) (int, error) {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		return 0, err
	}
	records, failure := collection.ListAll()
	if failure != nil {
		return 0, sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	return len(records), nil
}

// SetBlobSha writes a new sha on one blob record.
func SetBlobSha(sandbox *api.Sandbox, self *Backup, id int64, value string) error {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		return err
	}
	record, ok, failure := collection.FindByID(id)
	if failure != nil {
		return sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("blob %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(record.Update("sha", value))
}

// SetBlobValue writes a new value on one blob record.
func SetBlobValue(sandbox *api.Sandbox, self *Backup, id int64, value []byte) error {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		return err
	}
	record, ok, failure := collection.FindByID(id)
	if failure != nil {
		return sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("blob %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(record.Update("value", value))
}

// RemoveBlob deletes one blob record and everything nested under it.
func RemoveBlob(sandbox *api.Sandbox, self *Backup, id int64) error {
	collection, err := sandbox.Deps.OpinionatedAgnosDatabase.Collection(self.database, "blob")
	if err != nil {
		return err
	}
	record, ok, failure := collection.FindByID(id)
	if failure != nil {
		return sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure)
	}
	if !ok {
		return sandbox.Deps.StdDeps.Errorf("blob %d not found", id)
	}
	return sandbox.Deps.OpinionatedAgnosDatabase.Fail(record.Remove())
}

// newBlobFields is one insert into blob as the stored field map.
func newBlobFields(props BlobInput) map[string]any {
	return map[string]any{
		"sha":   props.Sha,
		"value": props.Value,
	}
}

// buildBlobRecord reads one stored blob record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildBlobRecord(sandbox *api.Sandbox, record databasedeps.Record) (BlobRecord, error) {
	built := BlobRecord{Id: record.ID}

	valueSha, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadString(record, "sha")
	if err != nil {
		return built, err
	}
	built.Sha = valueSha

	valueValue, err := sandbox.Deps.OpinionatedAgnosDatabase.ReadBytes(record, "value")
	if err != nil {
		return built, err
	}
	built.Value = valueValue

	return built, nil
}

// matchBlob is one BlobFilter applied to one record. A zero value
// never filters, so an empty filter keeps everything.
func matchBlob(sandbox *api.Sandbox, item BlobRecord, filter BlobFilter) bool {
	if !sandbox.Deps.OpinionatedAgnosDatabase.TextMatches(item.Sha, filter.ShaStartsWith, filter.ShaEquals) {
		return false
	}
	if !sandbox.Deps.OpinionatedAgnosDatabase.BytesMatches(item.Value, filter.ValueStartsWith, filter.ValueEquals) {
		return false
	}
	return true
}
