package backup

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// New builds the backup database from the Props its database.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a value over a prefix, so building one creates nothing until the first
// record is written. Props that Databases.New refuses are reported on stderr,
// and every method of the database then fails rather than panics; verify
// refuses every declaration that would build them.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *Backup {
	props := databasedeps.Props{
		Path: "data/backup",
		Schemas: []databasedeps.Schema{
			{
				Name: "blob",
				Fields: []databasedeps.Field{
					{Name: "sha", Type: databasedeps.Key, Required: true},
					{Name: "value", Type: databasedeps.Bytes, Required: true},
				},
			},
			{
				Name: "snapshot",
				Fields: []databasedeps.Field{
					{Name: "name", Type: databasedeps.Key, Required: true},
					{Name: "data", Type: databasedeps.Int, Required: true},
					{Name: "content", Type: databasedeps.Nested, Fields: []databasedeps.Field{
						{Name: "path", Type: databasedeps.String, Required: true},
						{Name: "sha", Type: databasedeps.String, Required: true}}},
				},
			},
		},
	}

	database, failure := sandbox.Deps.DatabaseDeps.Databases.New(props)
	if failure != nil {
		sandbox.Deps.StdDeps.Eprintf("backup: %s \n", sandbox.Deps.OpinionatedAgnosDatabase.Fail(failure).Error())
	}

	self := Backup{sandbox: sandbox, database: database}

	self.AddBlob = func(props BlobInput) (BlobRecord, error) {
		return AddBlob(self.sandbox, &self, props)
	}
	self.FindBlobById = func(id int64) (BlobRecord, bool) {
		return FindBlobById(self.sandbox, &self, id)
	}
	self.FindBlobBySha = func(value string) (BlobRecord, bool) {
		return FindBlobBySha(self.sandbox, &self, value)
	}
	self.ListBlobs = func(filter BlobFilter) ([]BlobRecord, error) {
		return ListBlobs(self.sandbox, &self, filter)
	}
	self.ListBlobsPage = func(offset int, limit int) ([]BlobRecord, error) {
		return ListBlobsPage(self.sandbox, &self, offset, limit)
	}
	self.CountBlob = func() (int, error) {
		return CountBlob(self.sandbox, &self)
	}
	self.SetBlobSha = func(id int64, value string) error {
		return SetBlobSha(self.sandbox, &self, id, value)
	}
	self.SetBlobValue = func(id int64, value []byte) error {
		return SetBlobValue(self.sandbox, &self, id, value)
	}
	self.RemoveBlob = func(id int64) error {
		return RemoveBlob(self.sandbox, &self, id)
	}
	self.AddSnapshot = func(props SnapshotInput) (SnapshotRecord, error) {
		return AddSnapshot(self.sandbox, &self, props)
	}
	self.FindSnapshotById = func(id int64) (SnapshotRecord, bool) {
		return FindSnapshotById(self.sandbox, &self, id)
	}
	self.FindSnapshotByName = func(value string) (SnapshotRecord, bool) {
		return FindSnapshotByName(self.sandbox, &self, value)
	}
	self.ListSnapshots = func(filter SnapshotFilter) ([]SnapshotRecord, error) {
		return ListSnapshots(self.sandbox, &self, filter)
	}
	self.ListSnapshotsPage = func(offset int, limit int) ([]SnapshotRecord, error) {
		return ListSnapshotsPage(self.sandbox, &self, offset, limit)
	}
	self.CountSnapshot = func() (int, error) {
		return CountSnapshot(self.sandbox, &self)
	}
	self.SetSnapshotName = func(id int64, value string) error {
		return SetSnapshotName(self.sandbox, &self, id, value)
	}
	self.SetSnapshotData = func(id int64, value int64) error {
		return SetSnapshotData(self.sandbox, &self, id, value)
	}
	self.RemoveSnapshot = func(id int64) error {
		return RemoveSnapshot(self.sandbox, &self, id)
	}
	self.AddSnapshotContent = func(parentId int64, props SnapshotContentInput) (SnapshotContentRecord, error) {
		return AddSnapshotContent(self.sandbox, &self, parentId, props)
	}
	self.ListSnapshotContents = func(parentId int64) ([]SnapshotContentRecord, error) {
		return ListSnapshotContents(self.sandbox, &self, parentId)
	}

	return &self
}
