package backup

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	databasedeps "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/databasedeps"
)

// New builds the backup database from the Props its database.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a handle over a prefix, so building one creates nothing until the first
// record is written.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *Backup {
	props := databasedeps.Props{
		Path:    "data/backup",
		Schemas: []databasedeps.Schema{},
	}

	self := Backup{sandbox: sandbox}
	self.handle = sandbox.Deps.DatabaseDeps.Databases.New(props)

	return &self
}
