package static

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/server/route"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "static"
	self.AcceptMethods = []string{"GET"}
	self.Priority = 100
	self.ResponseType = "application/octet-stream"
	self.Segments = 0
	self.After = false
	self.Pattern = "/static/{*Item}"
	self.Category = "Assets"
	self.Help = "Serves one file from the embedded static assets"
	self.LongDescription = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Mount",
			Start:       0,
			End:         0,
			Type:        api.StringPath,
			Description: "the directory every static asset is served under",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "/static", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Item",
			Start:       1,
			End:         -1,
			Type:        api.StringPath,
			Description: "the asset path under assets/frontend/static, one or more segments",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "Sha",
			Key:         "sha",
			Fonts:       []api.ParameterFont{api.QueryParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the digest staticref stamped on the url; when it matches the asset the answer is cacheable forever",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.InternalPurehandler = func(bound *api.Route, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, bound, entries, response)
	}

	return self
}
