// Code generated by agnos. DO NOT EDIT.

package list_backoffice_api_tokens_page

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/generated.new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "list_backoffice_api_tokens_page"
	self.Methods = []string{"GET"}
	self.Priority = 100
	self.ResponseType = "text/html"
	self.Segments = 2
	self.Pattern = "/admin/list-backoffice-api-tokens"
	self.Category = "Backoffice API Tokens"
	self.Summary = "Lists your API tokens, or every user's for a root"
	self.Description = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "AdminListBackofficeApiTokens",
			Start:       0,
			End:         1,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/admin/list-backoffice-api-tokens", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "Notice",
			Key:         "notice",
			Sources:     []api.ParameterSource{api.SourceQuery},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "the outcome code of the last revoke",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
