package backoffice_root_guard

// Input is every value this route reads off a request, one field per entry
// of its route.yaml: FullRoute, the whole request path, then one per entry of
// `paths` and one per entry of `parameters`, then Body when the route declares
// one, each tagged with the id the generic Run fills it by. Handle is handed
// one, already filled.
// Generated by `agnos build` — do not edit by hand.
type Input struct {
	FullRoute string `id:"FullRoute"`
	AdminRoot string `id:"AdminRoot"`
}
