package health

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
)

// NewRoute builds this route's declaration — the whole of what its route.yaml
// says — and closes RouteHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) api.Route {
	route := api.Route{}

	route.Name = "health"
	route.AcceptMethods = []string{"GET"}
	route.Priority = 0
	route.Category = "Server"
	route.Help = "Reports that the server is up"
	route.LongDescription = ""
	route.Examples = []string{"curl localhost:8080/health"}

	return route
}
