package server

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
)

// NewServer builds the http surface of the sandbox: Routes, one entry per
// sandbox/internal/routes/<name>/ built by that package's generated NewRoute —
// in run order, the lowest `priority` first and the route fixing the most
// literal segments first within one rung — Serve, the dispatch that reads a
// request against them, and Fail, which hands one failure to the project's own
// handler for it. Generated by `agnos build` — do not edit by hand.
func NewServer(sandbox *api.Sandbox) api.Server {
	server := api.Server{}

	server.Routes = []api.Route{}

	server.Serve = func(props api.ServeProps) error {
		return ServerMain(sandbox, props)
	}

	server.NewRouteBase = func() api.Route {
		return
	}

	return server
}
