package server

import (
	api "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	routes_health "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routes/health"
	routes_homepage "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routes/homepage"
	routes_list_links "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routes/list_links"
	routes_manage_links "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routes/manage_links"
	routes_redirect "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routes/redirect"
	routes_shortner "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routes/shortner"
	routes_static "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routes/static"
)

// NewServer builds the http surface of the sandbox: Routes, one entry per
// sandbox/internal/routes/<name>/ built by that package's generated NewRoute —
// in match order, the route fixing the most literal segments first — and Serve,
// the dispatch that reads a request against them. Generated by
// `agnos build` — do not edit by hand.
func NewServer(sandbox *api.Sandbox) api.Server {
	server := api.Server{}

	server.Routes = []api.Route{
		routes_manage_links.NewRoute(sandbox),
		routes_list_links.NewRoute(sandbox),
		routes_redirect.NewRoute(sandbox),
		routes_shortner.NewRoute(sandbox),
		routes_health.NewRoute(sandbox),
		routes_static.NewRoute(sandbox),
		routes_homepage.NewRoute(sandbox),
	}

	server.Serve = func(props api.ServeProps) error {
		return ServerMain(sandbox, props)
	}

	return server
}
