package database_dir

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "database_dir"
	self.Identifiers = []string{}
	self.Priority = 6
	self.Segments = 0
	self.Strict = false
	self.Pattern = "*"
	self.Category = "Middleware"
	self.Summary = "Read --database in front of every command"
	self.Description = "Runs in front of every command line and answers none of them. It reads\n--database into sandbox.Config.DatabaseDir, the folder every database's\nkey-prefix is a path inside, so `start-server --database var/app` keeps\nevery database there. The folder is relative to the directory the command\nruns from, its segments lower-case letters, digits, - and _: the store\nresolves every key under that directory and spells any other character\nescaped, so only such a path names the same folder on disk. No command\ndeclares the flag itself."
	self.Examples = []string{}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         -1,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerPrefix, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Database",
			Keys:        []string{"--database"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "data",
			HasDefault:  true,
			Pattern:     "^[a-z0-9_-]+(/[a-z0-9_-]+)*/?$",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the folder every database lives under, relative to where the command runs, lower-case letters, digits, - and _ (defaults to data)",
		},
	}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
