package api

import (
	opinatedagnoscli "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/OpinatedAgnosCli"
)

// Cli is the CLI surface of the sandbox: every command the project declares,
// and the dispatch that reads a command line against them. It is the
// OpinatedAgnosCli contract's Cli, built by
// sandbox/internal/generated/cli/cli/new.go, generated by `agnos build`.
type Cli = opinatedagnoscli.Cli

// ExitOk reports that the command did what it was asked to do.
const ExitOk = opinatedagnoscli.ExitOk

// ExitFailure reports that a well-formed command could not be carried out.
const ExitFailure = opinatedagnoscli.ExitFailure

// ExitUsage reports that the command line itself was wrong — an unknown
// command or flag, a missing operand, an unparsable amount.
const ExitUsage = opinatedagnoscli.ExitUsage
