package api

// Cli is the CLI surface of the sandbox: every command the project declares,
// and the dispatch that reads a command line against them. It is built by
// sandbox/internal/cli/new.go, generated by `agnos build`.
type Cli struct {
	// CliMain is the generated dispatch-and-parse entry point (see
	// sandbox/internal/cli/climain.go).
	CliMain func(args []string) int
	// Commands is every command the project declares, in listing order,
	// each built by the generated NewCommand of its own package. The
	// dispatch reads the command line against these declarations; a caller
	// holding the sandbox reads the same surface without one.
	Commands []Command
}

const (
	// ExitOk reports that the command did what it was asked to do.
	ExitOk = 0
	// ExitFailure reports that a well-formed command could not be carried
	// out.
	ExitFailure = 1
	// ExitUsage reports that the command line itself was wrong — an unknown
	// command or flag, a missing operand, an unparsable amount. Every such
	// error exits with this one code, whichever command produced it.
	ExitUsage = 2
)
