package api

// DefaultDatabaseDir is the folder every database of the project lives under
// when no command line says otherwise: `--database` defaults to it, and a
// project used as a lib keeps it.
const DefaultDatabaseDir = "data"

// DatabaseConfig is the database layer's part of the Config: api.Config
// embeds it, so its field is read as sandbox.Config.DatabaseDir. Generated by
// `agnos build` while database is on.
type DatabaseConfig struct {
	// DatabaseDir is the folder every database of the project lives under,
	// relative to the directory the program runs from, its segments lower-case
	// letters, digits, - and _: a database.yaml's key-prefix is a path inside
	// it. The database-dir middleware sets it from `--database` in front of
	// every command line; NewConfig starts it at DefaultDatabaseDir.
	DatabaseDir string
}
