// Code generated by agnos. DO NOT EDIT.

package api

import (
	opinionatedagnosserver "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/OpinionatedAgnosServer"
)

// Server is the http surface of the sandbox: every route the project declares,
// and the dispatch that reads a request against them. It is the
// OpinionatedAgnosServer contract's Server, built by
// sandbox/internal/server/generated.new.go, generated by `agnos build`.
type Server = opinionatedagnosserver.Server

// ServeProps describes one run of the http server: the address to listen on
// — host:port, a bare port, or a range of ports tried in turn — and its
// timeouts.
type ServeProps = opinionatedagnosserver.ServeProps

// StatusOK reports that the route did what it was asked to do.
const StatusOK = opinionatedagnosserver.StatusOK

// StatusCreated reports that the route created what it was asked for.
const StatusCreated = opinionatedagnosserver.StatusCreated

// StatusNoContent reports success with nothing to send back.
const StatusNoContent = opinionatedagnosserver.StatusNoContent

// StatusMovedPermanently sends the caller to Location for good.
const StatusMovedPermanently = opinionatedagnosserver.StatusMovedPermanently

// StatusFound sends the caller to Location this once.
const StatusFound = opinionatedagnosserver.StatusFound

// StatusSeeOther sends the caller to Location with a GET, after a
// form was handled.
const StatusSeeOther = opinionatedagnosserver.StatusSeeOther

// StatusNotModified reports that the caller's cached copy is current.
const StatusNotModified = opinionatedagnosserver.StatusNotModified

// StatusTemporaryRedirect sends the caller to Location this once,
// keeping its method.
const StatusTemporaryRedirect = opinionatedagnosserver.StatusTemporaryRedirect

// StatusPermanentRedirect sends the caller to Location for good,
// keeping its method.
const StatusPermanentRedirect = opinionatedagnosserver.StatusPermanentRedirect

// StatusBadRequest reports a request the dispatch could not bind: a
// missing required field, an unparsable value, one out of range, or a
// body the declared schema rejects.
const StatusBadRequest = opinionatedagnosserver.StatusBadRequest

// StatusUnauthorized reports a request that carries no valid
// credentials.
const StatusUnauthorized = opinionatedagnosserver.StatusUnauthorized

// StatusForbidden reports credentials that are valid and not enough.
const StatusForbidden = opinionatedagnosserver.StatusForbidden

// StatusNotFound reports that no declared route matches the path.
const StatusNotFound = opinionatedagnosserver.StatusNotFound

// StatusMethodNotAllowed reports a path a route matches under another
// method.
const StatusMethodNotAllowed = opinionatedagnosserver.StatusMethodNotAllowed

// StatusConflict reports a well-formed request the current state refuses.
const StatusConflict = opinionatedagnosserver.StatusConflict

// StatusPayloadTooLarge reports a body longer than the route's
// max-bytes.
const StatusPayloadTooLarge = opinionatedagnosserver.StatusPayloadTooLarge

// StatusUnsupportedMediaType reports a content type the route does not
// declare.
const StatusUnsupportedMediaType = opinionatedagnosserver.StatusUnsupportedMediaType

// StatusUnprocessableEntity reports a well-formed request whose content
// breaks a rule of the domain.
const StatusUnprocessableEntity = opinionatedagnosserver.StatusUnprocessableEntity

// StatusTooManyRequests reports a caller over its rate.
const StatusTooManyRequests = opinionatedagnosserver.StatusTooManyRequests

// StatusInternalServerError reports a well-formed request the route could not carry
// out.
const StatusInternalServerError = opinionatedagnosserver.StatusInternalServerError

// StatusServiceUnavailable reports a server that cannot answer right now.
const StatusServiceUnavailable = opinionatedagnosserver.StatusServiceUnavailable
