// Code generated by agnos. DO NOT EDIT.

package api

import (
	opinionatedagnoscli "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/OpinionatedAgnosCli"
)

// Cli is the CLI surface of the sandbox: every command the project declares,
// and the dispatch that reads a command line against them. It is the
// OpinionatedAgnosCli contract's Cli, built by
// sandbox/internal/cli/generated.new.go, generated by `agnos build`.
type Cli = opinionatedagnoscli.Cli

// ExitOk reports that the command did what it was asked to do.
const ExitOk = opinionatedagnoscli.ExitOk

// ExitFailure reports that a well-formed command could not be carried out.
const ExitFailure = opinionatedagnoscli.ExitFailure

// ExitUsage reports that the command line itself was wrong — an unknown
// command or flag, a missing operand, an unparsable amount.
const ExitUsage = opinionatedagnoscli.ExitUsage
