// Code generated by agnos. DO NOT EDIT.

package api

import (
	opinionatedagnoscli "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/OpinionatedAgnosCli"
)

// TriggerType is how a Trigger compares the text it is handed. It is the
// OpinionatedAgnosCli contract's own, shared by the cli and the server layer.
type TriggerType = opinionatedagnoscli.TriggerType

// TriggerEqual matches a text that is exactly the trigger's Value.
const TriggerEqual = opinionatedagnoscli.TriggerEqual

// TriggerPrefix matches a text that is the Value or continues it with a new
// segment: "/admin" matches "/admin/users", never "/administrator".
const TriggerPrefix = opinionatedagnoscli.TriggerPrefix

// TriggerTextPrefix matches a text that begins with the Value, whatever
// follows it.
const TriggerTextPrefix = opinionatedagnoscli.TriggerTextPrefix

// TriggerSuffix matches a text that ends with the Value.
const TriggerSuffix = opinionatedagnoscli.TriggerSuffix

// TriggerRegex matches a text the Value, a regular expression, matches.
const TriggerRegex = opinionatedagnoscli.TriggerRegex

// TriggerOneOf matches a text that is exactly one of the trigger's Values.
const TriggerOneOf = opinionatedagnoscli.TriggerOneOf

// Trigger is the condition one declared slice or value has to meet for its
// unit to run at all — the parsed form of one `trigger:` of a route.yaml or a
// command.yaml.
type Trigger = opinionatedagnoscli.Trigger
