// Code generated by agnos. DO NOT EDIT.

package api

// ServerSandbox is the server layer's part of the Sandbox: api.Sandbox embeds
// it, so its field is read as sandbox.Server. Generated by
// `agnos build` while server is on.
type ServerSandbox struct {
	// Server is the http surface, built by the Constructor of
	// sandbox/constructors/server.
	Server Server
}
