// Code generated by agnos. DO NOT EDIT.

package api

// CliSandbox is the cli layer's part of the Sandbox: api.Sandbox embeds it, so
// its field is read as sandbox.Cli. Generated by `agnos build`
// while cli is on.
type CliSandbox struct {
	// Cli is the cli surface, built by the Constructor of
	// sandbox/constructors/cli.
	Cli Cli
}
