package api

import "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"

type TriggerType int

const (
	EqualTrigger TriggerType = iota
	PrefixTrigger
	SuffixTrigger
	RegexTrigger
)

type Trigger struct {
	Exist bool
	Type  TriggerType
	Value string
}
type Path struct {
	Star        int
	End         int
	Description string
	Name        string
	Trigger     Trigger
}
type ParamenterFont int

const (
	HeaderParam ParamenterFont = iota
	QueryParam
)

type ParamenterType int

const (
	StringType ParamenterType = iota
	NumberType
	BooleanType
	DateTimeType
	StringArrayType
)

type Parameter struct {
	Name     string
	Font     []ParamenterFont
	Required bool
	Type     ParamenterType
}

type Header struct {
	Key   string
	Value string
}

type Route struct {
	Name            string
	AcceptMethods   []string
	Priority        int
	Category        string
	Help            string
	LongDescription string
	Parameters      []Parameter
	Paths           []Path
	IsActionable    func(entries *serverdeps.Request) bool
	Handler         func(entries *serverdeps.Request, response *serverdeps.Response) error
	Examples        []string
}

// Server is the http surface of the sandbox: every route the project declares,
// and the dispatch that reads a request against them. It is built by
// sandbox/internal/server/new.go, generated by `agnos build`.
type Server struct {
	// Serve is the generated route-and-dispatch entry point (see
	// sandbox/internal/server/servermain.go). It blocks until the server
	// stops.
	Serve func(props ServeProps) error
	// Routes is every http route the project declares, in run order —
	// lowest `priority` first, then most specific — each built by the
	// generated NewRoute of its own package. The dispatch reads a request
	// against these declarations; a caller holding the sandbox reads the
	// same surface without one.
	Routes []Route
	// Fail answers one failure with the project's own handler for it: it
	// reads route.Failure and calls the matching Handle* of
	// sandbox/internal/server/. It is a field rather than a call because a
	// route package may not import sandbox/internal/server — that package
	// imports every route — so this is how a generated ReadBody, or any
	// handler, reaches a file the project owns. Raise a failure through
	// routeio.Fail rather than calling this directly.
	Fail func(route *Route) error
}

// ServeProps describes one run of the http server: the address to listen on
// and the two timeouts, in milliseconds, a request and a response are held to.
type ServeProps struct {
	Addr           string
	ReadTimeoutMs  int
	WriteTimeoutMs int
}

const (
	// StatusOk reports that the route did what it was asked to do.
	StatusOk = 200
	// StatusCreated reports that the route created what it was asked for.
	StatusCreated = 201
	// StatusNoContent reports success with nothing to send back.
	StatusNoContent = 204
	// StatusBadRequest reports a request the dispatch could not bind: a
	// missing required field, an unparsable value, one out of range, or a
	// body the declared schema rejects.
	StatusBadRequest = 400
	// StatusNotFound reports that no declared route matches the path.
	StatusNotFound = 404
	// StatusMethodNotAllowed reports a path a route matches under another
	// method.
	StatusMethodNotAllowed = 405
	// StatusConflict reports a well-formed request the current state refuses.
	StatusConflict = 409
	// StatusPayloadTooLarge reports a body longer than the route's
	// max-bytes.
	StatusPayloadTooLarge = 413
	// StatusUnsupportedMedia reports a content type the route does not
	// declare.
	StatusUnsupportedMedia = 415
	// StatusFailure reports a well-formed request the route could not carry
	// out.
	StatusFailure = 500
)
