package api

import (
	opinatedagnosserver "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/OpinatedAgnosServer"
)

// Server is the http surface of the sandbox: every route the project declares,
// and the dispatch that reads a request against them. It is the
// OpinatedAgnosServer contract's Server, built by
// sandbox/internal/generated/server/server/new.go, generated by `agnos build`.
type Server = opinatedagnosserver.Server

// ServeProps describes one run of the http server: the address to listen on
// — host:port, a bare port, or a range of ports tried in turn — and its
// timeouts.
type ServeProps = opinatedagnosserver.ServeProps

// StatusOk reports that the route did what it was asked to do.
const StatusOk = opinatedagnosserver.StatusOk

// StatusCreated reports that the route created what it was asked for.
const StatusCreated = opinatedagnosserver.StatusCreated

// StatusNoContent reports success with nothing to send back.
const StatusNoContent = opinatedagnosserver.StatusNoContent

// StatusMovedPermanently sends the caller to Location for good.
const StatusMovedPermanently = opinatedagnosserver.StatusMovedPermanently

// StatusFound sends the caller to Location this once.
const StatusFound = opinatedagnosserver.StatusFound

// StatusSeeOther sends the caller to Location with a GET, after a
// form was handled.
const StatusSeeOther = opinatedagnosserver.StatusSeeOther

// StatusNotModified reports that the caller's cached copy is current.
const StatusNotModified = opinatedagnosserver.StatusNotModified

// StatusTemporaryRedirect sends the caller to Location this once,
// keeping its method.
const StatusTemporaryRedirect = opinatedagnosserver.StatusTemporaryRedirect

// StatusPermanentRedirect sends the caller to Location for good,
// keeping its method.
const StatusPermanentRedirect = opinatedagnosserver.StatusPermanentRedirect

// StatusBadRequest reports a request the dispatch could not bind: a
// missing required field, an unparsable value, one out of range, or a
// body the declared schema rejects.
const StatusBadRequest = opinatedagnosserver.StatusBadRequest

// StatusUnauthorized reports a request that carries no valid
// credentials.
const StatusUnauthorized = opinatedagnosserver.StatusUnauthorized

// StatusForbidden reports credentials that are valid and not enough.
const StatusForbidden = opinatedagnosserver.StatusForbidden

// StatusNotFound reports that no declared route matches the path.
const StatusNotFound = opinatedagnosserver.StatusNotFound

// StatusMethodNotAllowed reports a path a route matches under another
// method.
const StatusMethodNotAllowed = opinatedagnosserver.StatusMethodNotAllowed

// StatusConflict reports a well-formed request the current state refuses.
const StatusConflict = opinatedagnosserver.StatusConflict

// StatusPayloadTooLarge reports a body longer than the route's
// max-bytes.
const StatusPayloadTooLarge = opinatedagnosserver.StatusPayloadTooLarge

// StatusUnsupportedMedia reports a content type the route does not
// declare.
const StatusUnsupportedMedia = opinatedagnosserver.StatusUnsupportedMedia

// StatusUnprocessable reports a well-formed request whose content
// breaks a rule of the domain.
const StatusUnprocessable = opinatedagnosserver.StatusUnprocessable

// StatusTooManyRequests reports a caller over its rate.
const StatusTooManyRequests = opinatedagnosserver.StatusTooManyRequests

// StatusFailure reports a well-formed request the route could not carry
// out.
const StatusFailure = opinatedagnosserver.StatusFailure

// StatusUnavailable reports a server that cannot answer right now.
const StatusUnavailable = opinatedagnosserver.StatusUnavailable
