// Code generated by agnos. DO NOT EDIT.

package backoffice_same_origin

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/generated.new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "backoffice_same_origin"
	self.Methods = []string{"ANY"}
	self.Priority = 9
	self.ResponseType = "application/json"
	self.Segments = 0
	self.Pattern = "/admin/*"
	self.Category = "Middleware"
	self.Summary = "Refuses a request to /admin another site's page sent"
	self.Description = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Admin",
			Start:       0,
			End:         -1,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerPrefix, Value: "/admin", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "Origin",
			Key:         "origin",
			Sources:     []api.ParameterSource{api.SourceHeader},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "the origin of the page that sent the request, sent by the browser",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Host",
			Key:         "host",
			Sources:     []api.ParameterSource{api.SourceHeader},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "the host the request was sent to",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
