package start_server

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/commandprops"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the empty base of Deps.OpinionatedAgnosCli.NewCommand, and
// closes Handle over the sandbox as the handler behind it. It is
// called once by sandbox/internal/generated/cli/new.go, and what it returns
// is one entry of Cli.Commands: the declaration alone, which the lib's dispatch
// copies before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := sandbox.Deps.OpinionatedAgnosCli.NewCommand(sandbox.Deps.ArgvDeps)

	self.Name = "start_server"
	self.Identifiers = []string{"start-server"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "start-server"
	self.Category = "Server"
	self.Summary = "Start the http server"
	self.Description = "Opens the port and serves every route declared under\nsandbox/internal/routes, until the process is stopped. An interrupt\n(Ctrl+C) or a termination request stops it gracefully: no new request is\ntaken, and the ones in flight get --shutdown-timeout-ms to finish.\n"
	self.Examples = []string{"start-server", "start-server --addr 4000:5000"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Verb",
			Start:       0,
			End:         0,
			Type:        api.ArgString,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "start-server", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Addr",
			Keys:        []string{"--addr"},
			Type:        api.FlagString,
			Required:    false,
			Default:     "3000:4000",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "the port the server listens on, or a range of ports it takes the first free one of, with or without a host (8080, 4000:5000, 127.0.0.1:4000:5000, :8080)",
		},
		{
			Id:          "ReadTimeoutMs",
			Keys:        []string{"--read-timeout-ms"},
			Type:        api.FlagInteger,
			Required:    false,
			Default:     "10000",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "how long a request has to arrive, in milliseconds",
		},
		{
			Id:          "WriteTimeoutMs",
			Keys:        []string{"--write-timeout-ms"},
			Type:        api.FlagInteger,
			Required:    false,
			Default:     "10000",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "how long a response has to be written, in milliseconds",
		},
		{
			Id:          "ShutdownTimeoutMs",
			Keys:        []string{"--shutdown-timeout-ms"},
			Type:        api.FlagInteger,
			Required:    false,
			Default:     "10000",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
			Description: "how long the requests in flight have to finish once the server is asked to stop, in milliseconds (0 waits for them)",
		},
	}

	self.Handle = func(props *commandprops.CommandProps, input *Input, response *api.CommandResponse) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
