package health

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/server/route"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "health"
	self.AcceptMethods = []string{"GET"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 0
	self.After = false
	self.Pattern = "/health"
	self.Category = "Server"
	self.Help = "Reports that the server is up"
	self.LongDescription = ""
	self.Examples = []string{"curl localhost:8080/health"}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Route",
			Start:       0,
			End:         -1,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "/health", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.InternalPurehandler = func(bound *api.Route, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, bound, entries, response)
	}

	return self
}
