package api_add_backup_snapshot_reference

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "api_add_backup_snapshot_reference"
	self.Methods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 4
	self.Pattern = "/api/admin/root/add-backup-snapshot-reference"
	self.Category = "Backoffice Backups API"
	self.Summary = "Adds to an open snapshot one file whose content add-backup-blob already stored, by its sha; a path it already holds is replaced"
	self.Description = ""
	self.Examples = []string{"curl -X POST localhost:3000/api/admin/root/add-backup-snapshot-reference -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' -d '{\"id\":1,\"path\":\"backofficedb/backoffice-user/1/values/username\",\"sha\":\"<sha add-backup-blob answered>\"}'"}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "ApiAdminRootAddBackupSnapshotReference",
			Start:       0,
			End:         3,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/api/admin/root/add-backup-snapshot-reference", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "json",
		Required:    true,
		MaxBytes:    1048576,
		ContentType: "application/json",
		Schema:      BodySchema,
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
