package api_login

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/generated/server/route"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/generated/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "api_login"
	self.AcceptMethods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "application/json"
	self.Segments = 3
	self.Pattern = "/api/admin/login"
	self.Category = "Backoffice API"
	self.Help = "Signs a backoffice user in and answers a Bearer token"
	self.LongDescription = ""
	self.Examples = []string{"curl -X POST localhost:3000/api/admin/login -H 'Content-Type: application/json' -d '{\"username\":\"root\",\"password\":\"secret123\"}'"}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "ApiAdminLogin",
			Start:       0,
			End:         2,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "/api/admin/login", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "XClientIp",
			Key:         "x-client-ip",
			Fonts:       []api.ParameterFont{api.HeaderParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the ip the request came from, set by the server and never by the client",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "json",
		Required:    true,
		MaxBytes:    1048576,
		ContentType: "application/json",
		Schema:      BodySchema,
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
