package start_server

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
)

// NewCommand builds this command's declaration — the whole of what its
// entries.yaml says — and closes CommandHandler over the sandbox as the
// handler behind it. It is called once, by sandbox/internal/cli/new.go, and
// what it returns is one entry of Cli.Commands: the declaration alone, which
// the dispatch copies with api.BindCommand before binding a command line onto
// it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewCommand(sandbox *api.Sandbox) api.Command {
	command := api.NewCommand()

	command.Name = "start_server"
	command.Identifiers = []string{"start-server"}
	command.Category = "Server"
	command.Help = "Starts the http server"
	command.LongDescription = "Opens the port and serves every route declared under\nsandbox/internal/routeslist, until the process is stopped. An interrupt\n(Ctrl+C) or a termination request stops it gracefully: no new request is\ntaken, and the ones in flight get --shutdown-timeout-ms to finish.\n"
	command.Examples = []string{"start-server", "start-server --addr :3000"}
	command.Hidden = false

	command.Flags = []api.CommandFlag{
		{
			Id:          "addr",
			Type:        "string",
			Required:    false,
			Array:       false,
			Description: "the address the server listens on",
			Examples:    []string{"start-server --addr :3000"},
			Default:     ":8080",
			HasDefault:  true,
			Identifiers: []string{"--addr"},
		},
		{
			Id:          "read_timeout_ms",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "how long a request has to arrive, in milliseconds",
			Examples:    []string{"start-server --read-timeout-ms 30000"},
			Default:     "10000",
			HasDefault:  true,
			Identifiers: []string{"--read-timeout-ms"},
		},
		{
			Id:          "write_timeout_ms",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "how long a response has to be written, in milliseconds",
			Examples:    []string{"start-server --write-timeout-ms 30000"},
			Default:     "10000",
			HasDefault:  true,
			Identifiers: []string{"--write-timeout-ms"},
		},
		{
			Id:          "shutdown_timeout_ms",
			Type:        "int",
			Required:    false,
			Array:       false,
			Description: "how long the requests in flight have to finish once the server is asked to stop, in milliseconds (0 waits for them)",
			Examples:    []string{"start-server --shutdown-timeout-ms 5000"},
			Default:     "10000",
			HasDefault:  true,
			Identifiers: []string{"--shutdown-timeout-ms"},
		},
	}

	command.Args = []api.CommandArg{}

	command.Handler = func(bound *api.Command) int {
		return CommandHandler(sandbox, bound)
	}

	return *command
}
