package start_server

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/commandprops"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/generated/cli/command"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the generic base of sandbox/internal/generated/cli/command,
// and closes InternalPureHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/generated/cli/cli/new.go, and what it
// returns is one entry of Cli.Commands: the declaration alone, which the
// dispatch copies with api.BindCommand before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := command.NewCommand(sandbox)

	self.Name = "start_server"
	self.Identifiers = []string{"start-server"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "start-server"
	self.Category = "Server"
	self.Help = "Starts the http server"
	self.LongDescription = "Opens the port and serves every route declared under sandbox/internal/routeslist, until the process is stopped. An interrupt (Ctrl+C) or a termination request stops it gracefully: no new request is taken, and the ones in flight get --shutdown-timeout-ms to finish.\n\nThe secret that signs the backoffice sessions is read from the TESTE_SECRET environment variable, at least 32 characters (openssl rand -hex 32); without it the server does not start. It is never a flag, which every user of the machine reads, nor a file, which can end up committed with the code.\n\nThe session cookie is Secure and Strict-Transport-Security is sent, so the backoffice is served over https, by a reverse proxy that terminates TLS; --insecure-http turns both off, for local development over plain http.\n\nBehind one reverse proxy, bind the server to an address only the proxy reaches (--addr 127.0.0.1:3000) and pass --allow-x-forwarded-for: the client ip is then the last entry of X-Forwarded-For, the one the proxy appended. In nginx: proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for. With more layers in front (a load balancer, a CDN), have nginx resolve the client ip with its real_ip module and send proxy_set_header X-Forwarded-For $remote_addr."
	self.Examples = []string{"start-server", "start-server --addr 4000:5000", "start-server --addr 127.0.0.1:3000 --allow-x-forwarded-for"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "start-server", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Addr",
			Keys:        []string{"--addr"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "3000:4000",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the port the server listens on, or a range of ports it takes the first free one of, with or without a host (8080, 4000:5000, 127.0.0.1:4000:5000, :8080)",
		},
		{
			Id:          "ReadTimeoutMs",
			Keys:        []string{"--read-timeout-ms"},
			Type:        api.IntegerFlag,
			Required:    false,
			Default:     "10000",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "how long a request has to arrive, in milliseconds",
		},
		{
			Id:          "WriteTimeoutMs",
			Keys:        []string{"--write-timeout-ms"},
			Type:        api.IntegerFlag,
			Required:    false,
			Default:     "10000",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "how long a response has to be written, in milliseconds",
		},
		{
			Id:          "ShutdownTimeoutMs",
			Keys:        []string{"--shutdown-timeout-ms"},
			Type:        api.IntegerFlag,
			Required:    false,
			Default:     "10000",
			HasDefault:  true,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "how long the requests in flight have to finish once the server is asked to stop, in milliseconds (0 waits for them)",
		},
		{
			Id:          "AllowXForwardedFor",
			Keys:        []string{"--allow-x-forwarded-for"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "trust the last entry of X-Forwarded-For as the client ip: turn it on only behind one reverse proxy that appends it (nginx), with the server bound to an address only that proxy reaches (--addr 127.0.0.1:3000)",
		},
		{
			Id:          "InsecureHttp",
			Keys:        []string{"--insecure-http"},
			Type:        api.BooleanFlag,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "serve the backoffice over plain http, for local development only: the session cookie drops Secure and no Strict-Transport-Security is sent",
		},
	}

	self.InternalPureHandler = func(props *commandprops.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
