package keep

import (
	remoteavailable "github.com/MateusMoutinhoOrg/Keep/adapters/availables/standard"
	remotelib "github.com/MateusMoutinhoOrg/Keep/sandbox"
	remoteapi "github.com/MateusMoutinhoOrg/Keep/sandbox/api"

	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps"
	keep "github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/keep"
)

// Bind fills deps.Keep with github.com/MateusMoutinhoOrg/Keep, built from that repo's own
// adapters and handed over as the copy of its contract this project carries in
// sandbox/deps/keep.
//
// This file is generated by `agnos add-dep github.com/MateusMoutinhoOrg/Keep` and rewritten by
// `agnos set-dep keep`. The conversion below cannot live in the remote repo:
// keep.Sandbox has an import path inside this module, which that repo does not
// know when it publishes, and a top-level cast will not stand in for it —
// Go's type identity does not reach through named types, so two copies of a
// struct whose fields are named types are never the same type.
func Bind(deps *deps.Deps) {
	remote_deps := remoteavailable.New()
	remote_sandbox := remotelib.New(&remote_deps)
	deps.Keep = convSandbox(*remote_sandbox)
}

// convSandbox carries one value between the two copies of the contract.
func convSandbox(v remoteapi.Sandbox) keep.Sandbox {
	return keep.Sandbox{
		Databases: convDatabases(v.Databases),
		Info:      convInfo(v.Info),
	}
}

// convDatabases carries one value between the two copies of the contract.
func convDatabases(v remoteapi.Databases) keep.Databases {
	return keep.Databases{
		New: func(p0 keep.Props) keep.DatabaseHandle { return convDatabaseHandle(v.New(revProps(p0))) },
	}
}

// revProps carries one value between the two copies of the contract.
func revProps(v keep.Props) remoteapi.Props {
	return remoteapi.Props{
		Path:    v.Path,
		Schemas: revSliceSchema(v.Schemas),
	}
}

// revSliceSchema carries one value between the two copies of the contract.
func revSliceSchema(v []keep.Schema) []remoteapi.Schema {
	if v == nil {
		return nil
	}

	out := make([]remoteapi.Schema, len(v))
	for index := range v {
		out[index] = revSchema(v[index])
	}

	return out
}

// revSchema carries one value between the two copies of the contract.
func revSchema(v keep.Schema) remoteapi.Schema {
	return remoteapi.Schema{
		Name:  v.Name,
		Itens: revSliceItem(v.Itens),
	}
}

// revSliceItem carries one value between the two copies of the contract.
func revSliceItem(v []keep.Item) []remoteapi.Item {
	if v == nil {
		return nil
	}

	out := make([]remoteapi.Item, len(v))
	for index := range v {
		out[index] = revItem(v[index])
	}

	return out
}

// revItem carries one value between the two copies of the contract.
func revItem(v keep.Item) remoteapi.Item {
	return remoteapi.Item{
		Name:     v.Name,
		Type:     v.Type,
		Required: v.Required,
		Target:   v.Target,
		Itens:    revSliceItem(v.Itens),
	}
}

// convDatabaseHandle carries one value between the two copies of the contract.
func convDatabaseHandle(v remoteapi.DatabaseHandle) keep.DatabaseHandle {
	return keep.DatabaseHandle{
		Props: convProps(v.Props),
		GetSchema: func(p0 string) (keep.SchemaInstance, bool) {
			r0, r1 := v.GetSchema(p0)
			return convSchemaInstance(r0), r1
		},
	}
}

// convProps carries one value between the two copies of the contract.
func convProps(v remoteapi.Props) keep.Props {
	return keep.Props{
		Path:    v.Path,
		Schemas: convSliceSchema(v.Schemas),
	}
}

// convSliceSchema carries one value between the two copies of the contract.
func convSliceSchema(v []remoteapi.Schema) []keep.Schema {
	if v == nil {
		return nil
	}

	out := make([]keep.Schema, len(v))
	for index := range v {
		out[index] = convSchema(v[index])
	}

	return out
}

// convSchema carries one value between the two copies of the contract.
func convSchema(v remoteapi.Schema) keep.Schema {
	return keep.Schema{
		Name:  v.Name,
		Itens: convSliceItem(v.Itens),
	}
}

// convSliceItem carries one value between the two copies of the contract.
func convSliceItem(v []remoteapi.Item) []keep.Item {
	if v == nil {
		return nil
	}

	out := make([]keep.Item, len(v))
	for index := range v {
		out[index] = convItem(v[index])
	}

	return out
}

// convItem carries one value between the two copies of the contract.
func convItem(v remoteapi.Item) keep.Item {
	return keep.Item{
		Name:     v.Name,
		Type:     v.Type,
		Required: v.Required,
		Target:   v.Target,
		Itens:    convSliceItem(v.Itens),
	}
}

// convSchemaInstance carries one value between the two copies of the contract.
func convSchemaInstance(v remoteapi.SchemaInstance) keep.SchemaInstance {
	return keep.SchemaInstance{
		Items:  convSliceItem(v.Items),
		Prefix: v.Prefix,
		NewItem: func(p0 map[string]any) (keep.SchemaItem, *keep.Error) {
			r0, r1 := v.NewItem(p0)
			return convSchemaItem(r0), convPtrError(r1)
		},
		FindByKey: func(p0 string, p1 any) (keep.SchemaItem, bool) {
			r0, r1 := v.FindByKey(p0, p1)
			return convSchemaItem(r0), r1
		},
		FindById: func(p0 int64) (keep.SchemaItem, bool) {
			r0, r1 := v.FindById(p0)
			return convSchemaItem(r0), r1
		},
		ListAll: func() ([]keep.SchemaItem, *keep.Error) {
			r0, r1 := v.ListAll()
			return convSliceSchemaItem(r0), convPtrError(r1)
		},
		List: func(p0 int, p1 int) ([]keep.SchemaItem, *keep.Error) {
			r0, r1 := v.List(p0, p1)
			return convSliceSchemaItem(r0), convPtrError(r1)
		},
	}
}

// convSchemaItem carries one value between the two copies of the contract.
func convSchemaItem(v remoteapi.SchemaItem) keep.SchemaItem {
	return keep.SchemaItem{
		Items:  convSliceItem(v.Items),
		Prefix: v.Prefix,
		Id:     v.Id,
		Get: func(p0 string) (any, *keep.Error) {
			r0, r1 := v.Get(p0)
			return r0, convPtrError(r1)
		},
		GetLink: func(p0 string) (keep.SchemaItem, bool) {
			r0, r1 := v.GetLink(p0)
			return convSchemaItem(r0), r1
		},
		Update:            func(p0 string, p1 any) *keep.Error { return convPtrError(v.Update(p0, p1)) },
		Remove:            func() *keep.Error { return convPtrError(v.Remove()) },
		CheckKeysPresence: v.CheckKeysPresence,
		ListAll:           func(p0 string) []keep.SchemaItem { return convSliceSchemaItem(v.ListAll(p0)) },
		NewSubItem: func(p0 string, p1 map[string]any) (keep.SchemaItem, *keep.Error) {
			r0, r1 := v.NewSubItem(p0, p1)
			return convSchemaItem(r0), convPtrError(r1)
		},
		String: v.String,
	}
}

// convPtrError carries one value between the two copies of the contract.
func convPtrError(v *remoteapi.Error) *keep.Error {
	if v == nil {
		return nil
	}

	out := convError(*v)
	return &out
}

// convError carries one value between the two copies of the contract.
func convError(v remoteapi.Error) keep.Error {
	return keep.Error{
		Type:     v.Type,
		Key:      v.Key,
		KeyValue: v.KeyValue,
		Message:  v.Message,
	}
}

// convSliceSchemaItem carries one value between the two copies of the contract.
func convSliceSchemaItem(v []remoteapi.SchemaItem) []keep.SchemaItem {
	if v == nil {
		return nil
	}

	out := make([]keep.SchemaItem, len(v))
	for index := range v {
		out[index] = convSchemaItem(v[index])
	}

	return out
}

// convInfo carries one value between the two copies of the contract.
func convInfo(v remoteapi.Info) keep.Info {
	return keep.Info{
		Name:    v.Name,
		Version: v.Version,
	}
}
