package backoffice_session_auth

import (
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/api"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/deps/serverdeps"
	"github.com/MateusMoutinhoOrg/AgnosTeset/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the empty base of Deps.OpinionatedAgnosServer.NewRoute, and closes
// Handle over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/new.go, and what it returns
// is one entry of Server.Routes: the declaration alone, which the lib's
// dispatch copies before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in handler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := sandbox.Deps.OpinionatedAgnosServer.NewRoute()

	self.Name = "backoffice_session_auth"
	self.Methods = []string{"ANY"}
	self.Priority = 10
	self.ResponseType = "text/html"
	self.Segments = 0
	self.Pattern = "/admin/* !(/admin/login)"
	self.Category = "Middleware"
	self.Summary = "Requires a valid backoffice session on /admin, except /admin/login"
	self.Description = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Admin",
			Start:       0,
			End:         -1,
			Type:        api.PathString,
			Description: "",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerPrefix, Value: "/admin", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "NotLogin",
			Start:       0,
			End:         -1,
			Type:        api.PathString,
			Description: "the login route is reachable without a session",
			Trigger:     api.Trigger{Set: true, Type: api.TriggerEqual, Value: "/admin/login", Negate: true, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "AdminToken",
			Key:         "backoffice_session",
			Sources:     []api.ParameterSource{api.SourceCookie},
			Required:    false,
			Type:        api.ParameterString,
			Default:     "",
			HasDefault:  false,
			Description: "the session JWT set by POST /admin/login",
			Trigger:     api.Trigger{Set: false, Type: api.TriggerEqual, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.Handle = func(props *routeprops.RouteProps, input *Input, response *serverdeps.Response) error {
		return Handle(sandbox, props, input, response)
	}

	return self
}
